/*
    ____                      __      ____
   /\  _`\   __             /'_ `\   /\  _`\
   \ \ \L\_\/\_\    __  _  /\ \L\ \  \ \ \L\ \ _ __    ___
    \ \  _\/\/\ \  /\ \/'\ \/_> _ <_  \ \ ,__//\`'__\ / __`\
     \ \ \/  \ \ \ \/>  </   /\ \L\ \  \ \ \/ \ \ \/ /\ \L\ \
      \ \_\   \ \_\ /\_/\_\  \ \____/   \ \_\  \ \_\ \ \____/
       \/_/    \/_/ \//\/_/   \/___/     \/_/   \/_/  \/___/

               Fix8Pro FIX Engine and Framework

Copyright (C) 2010-19 Fix8 Market Technologies Pty Ltd (ABN 29 167 027 198)
All Rights Reserved. [http://www.fix8mt.com] <heretohelp@fix8mt.com>

THIS FILE IS PROPRIETARY AND  CONFIDENTIAL. NO PART OF THIS FILE MAY BE REPRODUCED,  STORED
IN A RETRIEVAL SYSTEM,  OR TRANSMITTED, IN ANY FORM OR ANY MEANS,  ELECTRONIC, PHOTOSTATIC,
RECORDED OR OTHERWISE, WITHOUT THE PRIOR AND  EXPRESS WRITTEN  PERMISSION  OF  FIX8  MARKET
TECHNOLOGIES PTY LTD.
*/

// Autogenerated on 2019-09-03 07:52:50.891352
// /home/sergey/src/f8/fix8pro/compiler/py/f8c/f8c.py --template ufe_java_fields ufe_cpp_fields ufe_cs_fields ufe_py_fields ufe_cpp_messages --output-dir ./generated --schema-dir /home/sergey/src/f8/fix8pro/schema/xml FIX50SP2 FIX42 FIX44 FIX40 FIX41 FIX43 FIX50 FIX50SP1
// DO NOT EDIT!

namespace UFE.UFEedClient
{
	namespace FIX42
	{
		namespace Field
		{

			// Account(1): STRING
			public static class Account
			{
				public const uint tag = 1;
			}

			// AdvId(2): STRING
			public static class AdvId
			{
				public const uint tag = 2;
			}

			// AdvRefID(3): STRING
			public static class AdvRefID
			{
				public const uint tag = 3;
			}

			// AdvSide(4): CHAR
			public static class AdvSide
			{
				public const uint tag = 4;
				public const char BUY = 'B';
				public const char SELL = 'S';
				public const char TRADE = 'T';
				public const char CROSS = 'X';
			}

			// AdvTransType(5): STRING
			public static class AdvTransType
			{
				public const uint tag = 5;
				public const string CANCEL = "C";
				public const string NEW = "N";
				public const string REPLACE = "R";
			}

			// AvgPx(6): PRICE
			public static class AvgPx
			{
				public const uint tag = 6;
			}

			// BeginSeqNo(7): INT
			public static class BeginSeqNo
			{
				public const uint tag = 7;
			}

			// BeginString(8): STRING
			public static class BeginString
			{
				public const uint tag = 8;
			}

			// BodyLength(9): INT
			public static class BodyLength
			{
				public const uint tag = 9;
			}

			// CheckSum(10): STRING
			public static class CheckSum
			{
				public const uint tag = 10;
			}

			// ClOrdID(11): STRING
			public static class ClOrdID
			{
				public const uint tag = 11;
			}

			// Commission(12): AMT
			public static class Commission
			{
				public const uint tag = 12;
			}

			// CommType(13): CHAR
			public static class CommType
			{
				public const uint tag = 13;
				public const char PER_SHARE = '1';
				public const char PERCENTAGE = '2';
				public const char ABSOLUTE = '3';
			}

			// CumQty(14): QTY
			public static class CumQty
			{
				public const uint tag = 14;
			}

			// Currency(15): CURRENCY
			public static class Currency
			{
				public const uint tag = 15;
			}

			// EndSeqNo(16): INT
			public static class EndSeqNo
			{
				public const uint tag = 16;
			}

			// ExecID(17): STRING
			public static class ExecID
			{
				public const uint tag = 17;
			}

			// ExecInst(18): MULTIPLEVALUESTRING
			public static class ExecInst
			{
				public const uint tag = 18;
				public const string STAY_ON_OFFERSIDE = "0";
				public const string NOT_HELD = "1";
				public const string WORK = "2";
				public const string GO_ALONG = "3";
				public const string OVER_THE_DAY = "4";
				public const string HELD = "5";
				public const string PARTICIPATE_DONT_INITIATE = "6";
				public const string STRICT_SCALE = "7";
				public const string TRY_TO_SCALE = "8";
				public const string STAY_ON_BIDSIDE = "9";
				public const string NO_CROSS = "A";
				public const string OK_TO_CROSS = "B";
				public const string CALL_FIRST = "C";
				public const string PERCENT_OF_VOLUME = "D";
				public const string DO_NOT_INCREASE = "E";
				public const string DO_NOT_REDUCE = "F";
				public const string ALL_OR_NONE = "G";
				public const string INSTITUTIONS_ONLY = "I";
				public const string LAST_PEG = "L";
				public const string MID_PRICE_PEG = "M";
				public const string NON_NEGOTIABLE = "N";
				public const string OPENING_PEG = "O";
				public const string MARKET_PEG = "P";
				public const string PRIMARY_PEG = "R";
				public const string SUSPEND = "S";
				public const string FIXED_PEG_TO_LOCAL_BEST_BID_OR_OFFER_AT_TIME_OF_ORDER = "T";
				public const string CUSTOMER_DISPLAY_INSTRUCTION = "U";
				public const string NETTING = "V";
				public const string PEG_TO_VWAP = "W";
			}

			// ExecRefID(19): STRING
			public static class ExecRefID
			{
				public const uint tag = 19;
			}

			// ExecTransType(20): CHAR
			public static class ExecTransType
			{
				public const uint tag = 20;
				public const char NEW = '0';
				public const char CANCEL = '1';
				public const char CORRECT = '2';
				public const char STATUS = '3';
			}

			// HandlInst(21): CHAR
			public static class HandlInst
			{
				public const uint tag = 21;
				public const char AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION = '1';
				public const char AUTOMATED_EXECUTION_ORDER_PUBLIC_BROKER_INTERVENTION_OK = '2';
				public const char MANUAL_ORDER_BEST_EXECUTION = '3';
			}

			// IDSource(22): STRING
			public static class IDSource
			{
				public const uint tag = 22;
				public const string CUSIP = "1";
				public const string SEDOL = "2";
				public const string QUIK = "3";
				public const string ISIN_NUMBER = "4";
				public const string RIC_CODE = "5";
				public const string ISO_CURRENCY_CODE = "6";
				public const string ISO_COUNTRY_CODE = "7";
				public const string EXCHANGE_SYMBOL = "8";
				public const string CONSOLIDATED_TAPE_ASSOCIATION = "9";
			}

			// IOIid(23): STRING
			public static class IOIid
			{
				public const uint tag = 23;
			}

			// IOIOthSvc(24): CHAR
			public static class IOIOthSvc
			{
				public const uint tag = 24;
			}

			// IOIQltyInd(25): CHAR
			public static class IOIQltyInd
			{
				public const uint tag = 25;
				public const char HIGH = 'H';
				public const char LOW = 'L';
				public const char MEDIUM = 'M';
			}

			// IOIRefID(26): STRING
			public static class IOIRefID
			{
				public const uint tag = 26;
			}

			// IOIShares(27): STRING
			public static class IOIShares
			{
				public const uint tag = 27;
				public const string LARGE = "L";
				public const string MEDIUM = "M";
				public const string SMALL = "S";
			}

			// IOITransType(28): CHAR
			public static class IOITransType
			{
				public const uint tag = 28;
				public const char CANCEL = 'C';
				public const char NEW = 'N';
				public const char REPLACE = 'R';
			}

			// LastCapacity(29): CHAR
			public static class LastCapacity
			{
				public const uint tag = 29;
				public const char AGENT = '1';
				public const char CROSS_AS_AGENT = '2';
				public const char CROSS_AS_PRINCIPAL = '3';
				public const char PRINCIPAL = '4';
			}

			// LastMkt(30): EXCHANGE
			public static class LastMkt
			{
				public const uint tag = 30;
			}

			// LastPx(31): PRICE
			public static class LastPx
			{
				public const uint tag = 31;
			}

			// LastShares(32): QTY
			public static class LastShares
			{
				public const uint tag = 32;
			}

			// LinesOfText(33): INT
			public static class LinesOfText
			{
				public const uint tag = 33;
			}

			// MsgSeqNum(34): INT
			public static class MsgSeqNum
			{
				public const uint tag = 34;
			}

			// MsgType(35): STRING
			public static class MsgType
			{
				public const uint tag = 35;
				public const string HEARTBEAT = "0";
				public const string TEST_REQUEST = "1";
				public const string RESEND_REQUEST = "2";
				public const string REJECT = "3";
				public const string SEQUENCE_RESET = "4";
				public const string LOGOUT = "5";
				public const string INDICATION_OF_INTEREST = "6";
				public const string ADVERTISEMENT = "7";
				public const string EXECUTION_REPORT = "8";
				public const string ORDER_CANCEL_REJECT = "9";
				public const string QUOTE_STATUS_REQUEST = "a";
				public const string LOGON = "A";
				public const string NEWS = "B";
				public const string QUOTE_ACKNOWLEDGEMENT = "b";
				public const string EMAIL = "C";
				public const string SECURITY_DEFINITION_REQUEST = "c";
				public const string ORDER_SINGLE = "D";
				public const string SECURITY_DEFINITION = "d";
				public const string ORDER_LIST = "E";
				public const string SECURITY_STATUS_REQUEST = "e";
				public const string SECURITY_STATUS = "f";
				public const string ORDER_CANCEL_REQUEST = "F";
				public const string ORDER_CANCEL_REPLACE_REQUEST = "G";
				public const string TRADING_SESSION_STATUS_REQUEST = "g";
				public const string ORDER_STATUS_REQUEST = "H";
				public const string TRADING_SESSION_STATUS = "h";
				public const string MASS_QUOTE = "i";
				public const string BUSINESS_MESSAGE_REJECT = "j";
				public const string ALLOCATION = "J";
				public const string LIST_CANCEL_REQUEST = "K";
				public const string BID_REQUEST = "k";
				public const string BID_RESPONSE = "l";
				public const string LIST_EXECUTE = "L";
				public const string LIST_STRIKE_PRICE = "m";
				public const string LIST_STATUS_REQUEST = "M";
				public const string LIST_STATUS = "N";
				public const string ALLOCATION_ACK = "P";
				public const string DONT_KNOW_TRADE = "Q";
				public const string QUOTE_REQUEST = "R";
				public const string QUOTE = "S";
				public const string SETTLEMENT_INSTRUCTIONS = "T";
				public const string MARKET_DATA_REQUEST = "V";
				public const string MARKET_DATA_SNAPSHOT_FULL_REFRESH = "W";
				public const string MARKET_DATA_INCREMENTAL_REFRESH = "X";
				public const string MARKET_DATA_REQUEST_REJECT = "Y";
				public const string QUOTE_CANCEL = "Z";
			}

			// NewSeqNo(36): INT
			public static class NewSeqNo
			{
				public const uint tag = 36;
			}

			// OrderID(37): STRING
			public static class OrderID
			{
				public const uint tag = 37;
			}

			// OrderQty(38): QTY
			public static class OrderQty
			{
				public const uint tag = 38;
			}

			// OrdStatus(39): CHAR
			public static class OrdStatus
			{
				public const uint tag = 39;
				public const char NEW = '0';
				public const char PARTIALLY_FILLED = '1';
				public const char FILLED = '2';
				public const char DONE_FOR_DAY = '3';
				public const char CANCELED = '4';
				public const char REPLACED = '5';
				public const char PENDING_CANCEL = '6';
				public const char STOPPED = '7';
				public const char REJECTED = '8';
				public const char SUSPENDED = '9';
				public const char PENDING_NEW = 'A';
				public const char CALCULATED = 'B';
				public const char EXPIRED = 'C';
				public const char ACCEPTED_FOR_BIDDING = 'D';
				public const char PENDING_REPLACE = 'E';
			}

			// OrdType(40): CHAR
			public static class OrdType
			{
				public const uint tag = 40;
				public const char MARKET = '1';
				public const char LIMIT = '2';
				public const char STOP = '3';
				public const char STOP_LIMIT = '4';
				public const char MARKET_ON_CLOSE = '5';
				public const char WITH_OR_WITHOUT = '6';
				public const char LIMIT_OR_BETTER = '7';
				public const char LIMIT_WITH_OR_WITHOUT = '8';
				public const char ON_BASIS = '9';
				public const char ON_CLOSE = 'A';
				public const char LIMIT_ON_CLOSE = 'B';
				public const char FOREX_C = 'C';
				public const char PREVIOUSLY_QUOTED = 'D';
				public const char PREVIOUSLY_INDICATED = 'E';
				public const char FOREX_F = 'F';
				public const char FOREX_G = 'G';
				public const char FOREX_H = 'H';
				public const char FUNARI = 'I';
				public const char PEGGED = 'P';
			}

			// OrigClOrdID(41): STRING
			public static class OrigClOrdID
			{
				public const uint tag = 41;
			}

			// OrigTime(42): UTCTIMESTAMP
			public static class OrigTime
			{
				public const uint tag = 42;
			}

			// PossDupFlag(43): BOOLEAN
			public static class PossDupFlag
			{
				public const uint tag = 43;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// Price(44): PRICE
			public static class Price
			{
				public const uint tag = 44;
			}

			// RefSeqNum(45): INT
			public static class RefSeqNum
			{
				public const uint tag = 45;
			}

			// RelatdSym(46): STRING
			public static class RelatdSym
			{
				public const uint tag = 46;
			}

			// Rule80A(47): CHAR
			public static class Rule80A
			{
				public const uint tag = 47;
				public const char AGENCY_SINGLE_ORDER = 'A';
				public const char SHORT_EXEMPT_TRANSACTION_B = 'B';
				public const char PROGRAM_ORDER_NON_INDEX_ARB_FOR_MEMBER_FIRM_ORG = 'C';
				public const char PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG = 'D';
				public const char REGISTERED_EQUITY_MARKET_MAKER_TRADES = 'E';
				public const char SHORT_EXEMPT_TRANSACTION_F = 'F';
				public const char SHORT_EXEMPT_TRANSACTION_H = 'H';
				public const char INDIVIDUAL_INVESTOR_SINGLE_ORDER = 'I';
				public const char PROGRAM_ORDER_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER = 'J';
				public const char PROGRAM_ORDER_NON_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER = 'K';
				public const char SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE = 'L';
				public const char PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER = 'M';
				public const char PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_MEMBER = 'N';
				public const char COMPETING_DEALER_TRADES_O = 'O';
				public const char PRINCIPAL = 'P';
				public const char COMPETING_DEALER_TRADES_R = 'R';
				public const char SPECIALIST_TRADES = 'S';
				public const char COMPETING_DEALER_TRADES_T = 'T';
				public const char PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_AGENCY = 'U';
				public const char ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER = 'W';
				public const char SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE = 'X';
				public const char PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_AGENCY = 'Y';
				public const char SHORT_EXEMPT_TRANSACTION_FOR_NON_MEMBER_COMPETING_MARKET_MAKER = 'Z';
			}

			// SecurityID(48): STRING
			public static class SecurityID
			{
				public const uint tag = 48;
			}

			// SenderCompID(49): STRING
			public static class SenderCompID
			{
				public const uint tag = 49;
			}

			// SenderSubID(50): STRING
			public static class SenderSubID
			{
				public const uint tag = 50;
			}

			// SendingDate(51): LOCALMKTDATE
			public static class SendingDate
			{
				public const uint tag = 51;
			}

			// SendingTime(52): UTCTIMESTAMP
			public static class SendingTime
			{
				public const uint tag = 52;
			}

			// Shares(53): QTY
			public static class Shares
			{
				public const uint tag = 53;
			}

			// Side(54): CHAR
			public static class Side
			{
				public const uint tag = 54;
				public const char BUY = '1';
				public const char SELL = '2';
				public const char BUY_MINUS = '3';
				public const char SELL_PLUS = '4';
				public const char SELL_SHORT = '5';
				public const char SELL_SHORT_EXEMPT = '6';
				public const char UNDISCLOSED = '7';
				public const char CROSS = '8';
				public const char CROSS_SHORT = '9';
			}

			// Symbol(55): STRING
			public static class Symbol
			{
				public const uint tag = 55;
			}

			// TargetCompID(56): STRING
			public static class TargetCompID
			{
				public const uint tag = 56;
			}

			// TargetSubID(57): STRING
			public static class TargetSubID
			{
				public const uint tag = 57;
			}

			// Text(58): STRING
			public static class Text
			{
				public const uint tag = 58;
			}

			// TimeInForce(59): CHAR
			public static class TimeInForce
			{
				public const uint tag = 59;
				public const char DAY = '0';
				public const char GOOD_TILL_CANCEL = '1';
				public const char AT_THE_OPENING = '2';
				public const char IMMEDIATE_OR_CANCEL = '3';
				public const char FILL_OR_KILL = '4';
				public const char GOOD_TILL_CROSSING = '5';
				public const char GOOD_TILL_DATE = '6';
			}

			// TransactTime(60): UTCTIMESTAMP
			public static class TransactTime
			{
				public const uint tag = 60;
			}

			// Urgency(61): CHAR
			public static class Urgency
			{
				public const uint tag = 61;
				public const char NORMAL = '0';
				public const char FLASH = '1';
				public const char BACKGROUND = '2';
			}

			// ValidUntilTime(62): UTCTIMESTAMP
			public static class ValidUntilTime
			{
				public const uint tag = 62;
			}

			// SettlmntTyp(63): CHAR
			public static class SettlmntTyp
			{
				public const uint tag = 63;
				public const char REGULAR = '0';
				public const char CASH = '1';
				public const char NEXT_DAY = '2';
				public const char T_PLUS_2 = '3';
				public const char T_PLUS_3 = '4';
				public const char T_PLUS_4 = '5';
				public const char FUTURE = '6';
				public const char WHEN_ISSUED = '7';
				public const char SELLERS_OPTION = '8';
				public const char T_PLUS_5 = '9';
			}

			// FutSettDate(64): LOCALMKTDATE
			public static class FutSettDate
			{
				public const uint tag = 64;
			}

			// SymbolSfx(65): STRING
			public static class SymbolSfx
			{
				public const uint tag = 65;
			}

			// ListID(66): STRING
			public static class ListID
			{
				public const uint tag = 66;
			}

			// ListSeqNo(67): INT
			public static class ListSeqNo
			{
				public const uint tag = 67;
			}

			// TotNoOrders(68): INT
			public static class TotNoOrders
			{
				public const uint tag = 68;
			}

			// ListExecInst(69): STRING
			public static class ListExecInst
			{
				public const uint tag = 69;
			}

			// AllocID(70): STRING
			public static class AllocID
			{
				public const uint tag = 70;
			}

			// AllocTransType(71): CHAR
			public static class AllocTransType
			{
				public const uint tag = 71;
				public const char NEW = '0';
				public const char REPLACE = '1';
				public const char CANCEL = '2';
				public const char PRELIMINARY = '3';
				public const char CALCULATED = '4';
				public const char CALCULATED_WITHOUT_PRELIMINARY = '5';
			}

			// RefAllocID(72): STRING
			public static class RefAllocID
			{
				public const uint tag = 72;
			}

			// NoOrders(73): INT
			public static class NoOrders
			{
				public const uint tag = 73;
			}

			// AvgPrxPrecision(74): INT
			public static class AvgPrxPrecision
			{
				public const uint tag = 74;
			}

			// TradeDate(75): LOCALMKTDATE
			public static class TradeDate
			{
				public const uint tag = 75;
			}

			// ExecBroker(76): STRING
			public static class ExecBroker
			{
				public const uint tag = 76;
			}

			// OpenClose(77): CHAR
			public static class OpenClose
			{
				public const uint tag = 77;
				public const char CLOSE = 'C';
				public const char OPEN = 'O';
			}

			// NoAllocs(78): INT
			public static class NoAllocs
			{
				public const uint tag = 78;
			}

			// AllocAccount(79): STRING
			public static class AllocAccount
			{
				public const uint tag = 79;
			}

			// AllocShares(80): QTY
			public static class AllocShares
			{
				public const uint tag = 80;
			}

			// ProcessCode(81): CHAR
			public static class ProcessCode
			{
				public const uint tag = 81;
				public const char REGULAR = '0';
				public const char SOFT_DOLLAR = '1';
				public const char STEP_IN = '2';
				public const char STEP_OUT = '3';
				public const char SOFT_DOLLAR_STEP_IN = '4';
				public const char SOFT_DOLLAR_STEP_OUT = '5';
				public const char PLAN_SPONSOR = '6';
			}

			// NoRpts(82): INT
			public static class NoRpts
			{
				public const uint tag = 82;
			}

			// RptSeq(83): INT
			public static class RptSeq
			{
				public const uint tag = 83;
			}

			// CxlQty(84): QTY
			public static class CxlQty
			{
				public const uint tag = 84;
			}

			// NoDlvyInst(85): INT
			public static class NoDlvyInst
			{
				public const uint tag = 85;
			}

			// DlvyInst(86): STRING
			public static class DlvyInst
			{
				public const uint tag = 86;
			}

			// AllocStatus(87): INT
			public static class AllocStatus
			{
				public const uint tag = 87;
				public const int ACCEPTED = 0;
				public const int REJECTED = 1;
				public const int PARTIAL_ACCEPT = 2;
				public const int RECEIVED = 3;
			}

			// AllocRejCode(88): INT
			public static class AllocRejCode
			{
				public const uint tag = 88;
				public const int UNKNOWN_ACCOUNT = 0;
				public const int INCORRECT_QUANTITY = 1;
				public const int INCORRECT_AVERAGE_PRICE = 2;
				public const int UNKNOWN_EXECUTING_BROKER_MNEMONIC = 3;
				public const int COMMISSION_DIFFERENCE = 4;
				public const int UNKNOWN_ORDERID = 5;
				public const int UNKNOWN_LISTID = 6;
				public const int OTHER = 7;
			}

			// Signature(89): DATA
			public static class Signature
			{
				public const uint tag = 89;
			}

			// SecureDataLen(90): LENGTH
			public static class SecureDataLen
			{
				public const uint tag = 90;
			}

			// SecureData(91): DATA
			public static class SecureData
			{
				public const uint tag = 91;
			}

			// BrokerOfCredit(92): STRING
			public static class BrokerOfCredit
			{
				public const uint tag = 92;
			}

			// SignatureLength(93): LENGTH
			public static class SignatureLength
			{
				public const uint tag = 93;
			}

			// EmailType(94): CHAR
			public static class EmailType
			{
				public const uint tag = 94;
				public const char NEW = '0';
				public const char REPLY = '1';
				public const char ADMIN_REPLY = '2';
			}

			// RawDataLength(95): LENGTH
			public static class RawDataLength
			{
				public const uint tag = 95;
			}

			// RawData(96): DATA
			public static class RawData
			{
				public const uint tag = 96;
			}

			// PossResend(97): BOOLEAN
			public static class PossResend
			{
				public const uint tag = 97;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// EncryptMethod(98): INT
			public static class EncryptMethod
			{
				public const uint tag = 98;
				public const int NONE = 0;
				public const int PKCS = 1;
				public const int DES = 2;
				public const int PKCS_DES = 3;
				public const int PGP_DES = 4;
				public const int PGP_DES_MD5 = 5;
				public const int PEM_DES_MD5 = 6;
			}

			// StopPx(99): PRICE
			public static class StopPx
			{
				public const uint tag = 99;
			}

			// ExDestination(100): EXCHANGE
			public static class ExDestination
			{
				public const uint tag = 100;
			}

			// CxlRejReason(102): INT
			public static class CxlRejReason
			{
				public const uint tag = 102;
				public const int TOO_LATE_TO_CANCEL = 0;
				public const int UNKNOWN_ORDER = 1;
				public const int BROKER_OPTION = 2;
				public const int ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS = 3;
			}

			// OrdRejReason(103): INT
			public static class OrdRejReason
			{
				public const uint tag = 103;
				public const int BROKER_OPTION = 0;
				public const int UNKNOWN_SYMBOL = 1;
				public const int EXCHANGE_CLOSED = 2;
				public const int ORDER_EXCEEDS_LIMIT = 3;
				public const int TOO_LATE_TO_ENTER = 4;
				public const int UNKNOWN_ORDER = 5;
				public const int DUPLICATE_ORDER = 6;
				public const int DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER = 7;
				public const int STALE_ORDER = 8;
			}

			// IOIQualifier(104): CHAR
			public static class IOIQualifier
			{
				public const uint tag = 104;
				public const char ALL_OR_NONE = 'A';
				public const char AT_THE_CLOSE = 'C';
				public const char IN_TOUCH_WITH = 'I';
				public const char LIMIT = 'L';
				public const char MORE_BEHIND = 'M';
				public const char AT_THE_OPEN = 'O';
				public const char TAKING_A_POSITION = 'P';
				public const char AT_THE_MARKET = 'Q';
				public const char READY_TO_TRADE = 'R';
				public const char PORTFOLIO_SHOW_N = 'S';
				public const char THROUGH_THE_DAY = 'T';
				public const char VERSUS = 'V';
				public const char INDICATION = 'W';
				public const char CROSSING_OPPORTUNITY = 'X';
				public const char AT_THE_MIDPOINT = 'Y';
				public const char PRE_OPEN = 'Z';
			}

			// WaveNo(105): STRING
			public static class WaveNo
			{
				public const uint tag = 105;
			}

			// Issuer(106): STRING
			public static class Issuer
			{
				public const uint tag = 106;
			}

			// SecurityDesc(107): STRING
			public static class SecurityDesc
			{
				public const uint tag = 107;
			}

			// HeartBtInt(108): INT
			public static class HeartBtInt
			{
				public const uint tag = 108;
			}

			// ClientID(109): STRING
			public static class ClientID
			{
				public const uint tag = 109;
			}

			// MinQty(110): QTY
			public static class MinQty
			{
				public const uint tag = 110;
			}

			// MaxFloor(111): QTY
			public static class MaxFloor
			{
				public const uint tag = 111;
			}

			// TestReqID(112): STRING
			public static class TestReqID
			{
				public const uint tag = 112;
			}

			// ReportToExch(113): BOOLEAN
			public static class ReportToExch
			{
				public const uint tag = 113;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// LocateReqd(114): BOOLEAN
			public static class LocateReqd
			{
				public const uint tag = 114;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// OnBehalfOfCompID(115): STRING
			public static class OnBehalfOfCompID
			{
				public const uint tag = 115;
			}

			// OnBehalfOfSubID(116): STRING
			public static class OnBehalfOfSubID
			{
				public const uint tag = 116;
			}

			// QuoteID(117): STRING
			public static class QuoteID
			{
				public const uint tag = 117;
			}

			// NetMoney(118): AMT
			public static class NetMoney
			{
				public const uint tag = 118;
			}

			// SettlCurrAmt(119): AMT
			public static class SettlCurrAmt
			{
				public const uint tag = 119;
			}

			// SettlCurrency(120): CURRENCY
			public static class SettlCurrency
			{
				public const uint tag = 120;
			}

			// ForexReq(121): BOOLEAN
			public static class ForexReq
			{
				public const uint tag = 121;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// OrigSendingTime(122): UTCTIMESTAMP
			public static class OrigSendingTime
			{
				public const uint tag = 122;
			}

			// GapFillFlag(123): BOOLEAN
			public static class GapFillFlag
			{
				public const uint tag = 123;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// NoExecs(124): INT
			public static class NoExecs
			{
				public const uint tag = 124;
			}

			// CxlType(125):  CHAR
			public static class CxlType
			{
				public const uint tag = 125;
			}

			// ExpireTime(126): UTCTIMESTAMP
			public static class ExpireTime
			{
				public const uint tag = 126;
			}

			// DKReason(127): CHAR
			public static class DKReason
			{
				public const uint tag = 127;
				public const char UNKNOWN_SYMBOL = 'A';
				public const char WRONG_SIDE = 'B';
				public const char QUANTITY_EXCEEDS_ORDER = 'C';
				public const char NO_MATCHING_ORDER = 'D';
				public const char PRICE_EXCEEDS_LIMIT = 'E';
				public const char OTHER = 'Z';
			}

			// DeliverToCompID(128): STRING
			public static class DeliverToCompID
			{
				public const uint tag = 128;
			}

			// DeliverToSubID(129): STRING
			public static class DeliverToSubID
			{
				public const uint tag = 129;
			}

			// IOINaturalFlag(130): BOOLEAN
			public static class IOINaturalFlag
			{
				public const uint tag = 130;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// QuoteReqID(131): STRING
			public static class QuoteReqID
			{
				public const uint tag = 131;
			}

			// BidPx(132): PRICE
			public static class BidPx
			{
				public const uint tag = 132;
			}

			// OfferPx(133): PRICE
			public static class OfferPx
			{
				public const uint tag = 133;
			}

			// BidSize(134): QTY
			public static class BidSize
			{
				public const uint tag = 134;
			}

			// OfferSize(135): QTY
			public static class OfferSize
			{
				public const uint tag = 135;
			}

			// NoMiscFees(136): INT
			public static class NoMiscFees
			{
				public const uint tag = 136;
			}

			// MiscFeeAmt(137): AMT
			public static class MiscFeeAmt
			{
				public const uint tag = 137;
			}

			// MiscFeeCurr(138): CURRENCY
			public static class MiscFeeCurr
			{
				public const uint tag = 138;
			}

			// MiscFeeType(139): CHAR
			public static class MiscFeeType
			{
				public const uint tag = 139;
				public const char REGULATORY = '1';
				public const char TAX = '2';
				public const char LOCAL_COMMISSION = '3';
				public const char EXCHANGE_FEES = '4';
				public const char STAMP = '5';
				public const char LEVY = '6';
				public const char OTHER = '7';
				public const char MARKUP = '8';
				public const char CONSUMPTION_TAX = '9';
			}

			// PrevClosePx(140): PRICE
			public static class PrevClosePx
			{
				public const uint tag = 140;
			}

			// ResetSeqNumFlag(141): BOOLEAN
			public static class ResetSeqNumFlag
			{
				public const uint tag = 141;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// SenderLocationID(142): STRING
			public static class SenderLocationID
			{
				public const uint tag = 142;
			}

			// TargetLocationID(143): STRING
			public static class TargetLocationID
			{
				public const uint tag = 143;
			}

			// OnBehalfOfLocationID(144): STRING
			public static class OnBehalfOfLocationID
			{
				public const uint tag = 144;
			}

			// DeliverToLocationID(145): STRING
			public static class DeliverToLocationID
			{
				public const uint tag = 145;
			}

			// NoRelatedSym(146): INT
			public static class NoRelatedSym
			{
				public const uint tag = 146;
			}

			// Subject(147): STRING
			public static class Subject
			{
				public const uint tag = 147;
			}

			// Headline(148): STRING
			public static class Headline
			{
				public const uint tag = 148;
			}

			// URLLink(149): STRING
			public static class URLLink
			{
				public const uint tag = 149;
			}

			// ExecType(150): CHAR
			public static class ExecType
			{
				public const uint tag = 150;
				public const char NEW = '0';
				public const char PARTIAL_FILL = '1';
				public const char FILL = '2';
				public const char DONE_FOR_DAY = '3';
				public const char CANCELED = '4';
				public const char REPLACE = '5';
				public const char PENDING_CANCEL = '6';
				public const char STOPPED = '7';
				public const char REJECTED = '8';
				public const char SUSPENDED = '9';
				public const char PENDING_NEW = 'A';
				public const char CALCULATED = 'B';
				public const char EXPIRED = 'C';
				public const char RESTATED = 'D';
				public const char PENDING_REPLACE = 'E';
			}

			// LeavesQty(151): QTY
			public static class LeavesQty
			{
				public const uint tag = 151;
			}

			// CashOrderQty(152): QTY
			public static class CashOrderQty
			{
				public const uint tag = 152;
			}

			// AllocAvgPx(153): PRICE
			public static class AllocAvgPx
			{
				public const uint tag = 153;
			}

			// AllocNetMoney(154): AMT
			public static class AllocNetMoney
			{
				public const uint tag = 154;
			}

			// SettlCurrFxRate(155): FLOAT
			public static class SettlCurrFxRate
			{
				public const uint tag = 155;
			}

			// SettlCurrFxRateCalc(156): CHAR
			public static class SettlCurrFxRateCalc
			{
				public const uint tag = 156;
				public const char MULTIPLY = 'M';
				public const char DIVIDE = 'D';
			}

			// NumDaysInterest(157): INT
			public static class NumDaysInterest
			{
				public const uint tag = 157;
			}

			// AccruedInterestRate(158): FLOAT
			public static class AccruedInterestRate
			{
				public const uint tag = 158;
			}

			// AccruedInterestAmt(159): AMT
			public static class AccruedInterestAmt
			{
				public const uint tag = 159;
			}

			// SettlInstMode(160): CHAR
			public static class SettlInstMode
			{
				public const uint tag = 160;
				public const char DEFAULT = '0';
				public const char STANDING_INSTRUCTIONS_PROVIDED = '1';
				public const char SPECIFIC_ALLOCATION_ACCOUNT_OVERRIDING = '2';
				public const char SPECIFIC_ALLOCATION_ACCOUNT_STANDING = '3';
			}

			// AllocText(161): STRING
			public static class AllocText
			{
				public const uint tag = 161;
			}

			// SettlInstID(162): STRING
			public static class SettlInstID
			{
				public const uint tag = 162;
			}

			// SettlInstTransType(163): CHAR
			public static class SettlInstTransType
			{
				public const uint tag = 163;
				public const char CANCEL = 'C';
				public const char NEW = 'N';
				public const char REPLACE = 'R';
			}

			// EmailThreadID(164): STRING
			public static class EmailThreadID
			{
				public const uint tag = 164;
			}

			// SettlInstSource(165): CHAR
			public static class SettlInstSource
			{
				public const uint tag = 165;
				public const char BROKERS_INSTRUCTIONS = '1';
				public const char INSTITUTIONS_INSTRUCTIONS = '2';
			}

			// SettlLocation(166): STRING
			public static class SettlLocation
			{
				public const uint tag = 166;
				public const string CEDEL = "CED";
				public const string DEPOSITORY_TRUST_COMPANY = "DTC";
				public const string EUROCLEAR = "EUR";
				public const string FEDERAL_BOOK_ENTRY = "FED";
				public const string LOCAL_MARKET_SETTLE_LOCATION = "ISO Country Code";
				public const string PHYSICAL = "PNY";
				public const string PARTICIPANT_TRUST_COMPANY = "PTC";
			}

			// SecurityType(167): STRING
			public static class SecurityType
			{
				public const uint tag = 167;
				public const string WILDCARD_ENTRY = "?";
				public const string BANKERS_ACCEPTANCE = "BA";
				public const string CONVERTIBLE_BOND = "CB";
				public const string CERTIFICATE_OF_DEPOSIT = "CD";
				public const string COLLATERALIZE_MORTGAGE_OBLIGATION = "CMO";
				public const string CORPORATE_BOND = "CORP";
				public const string COMMERCIAL_PAPER = "CP";
				public const string CORPORATE_PRIVATE_PLACEMENT = "CPP";
				public const string COMMON_STOCK = "CS";
				public const string FEDERAL_HOUSING_AUTHORITY = "FHA";
				public const string FEDERAL_HOME_LOAN = "FHL";
				public const string FEDERAL_NATIONAL_MORTGAGE_ASSOCIATION = "FN";
				public const string FOREIGN_EXCHANGE_CONTRACT = "FOR";
				public const string FUTURE = "FUT";
				public const string GOVERNMENT_NATIONAL_MORTGAGE_ASSOCIATION = "GN";
				public const string TREASURIES_PLUS_AGENCY_DEBENTURE = "GOVT";
				public const string MORTGAGE_IOETTE = "IET";
				public const string MUTUAL_FUND = "MF";
				public const string MORTGAGE_INTEREST_ONLY = "MIO";
				public const string MORTGAGE_PRINCIPAL_ONLY = "MPO";
				public const string MORTGAGE_PRIVATE_PLACEMENT = "MPP";
				public const string MISCELLANEOUS_PASS_THRU = "MPT";
				public const string MUNICIPAL_BOND = "MUNI";
				public const string NO_ISITC_SECURITY_TYPE = "NONE";
				public const string OPTION = "OPT";
				public const string PREFERRED_STOCK = "PS";
				public const string REPURCHASE_AGREEMENT = "RP";
				public const string REVERSE_REPURCHASE_AGREEMENT = "RVRP";
				public const string STUDENT_LOAN_MARKETING_ASSOCIATION = "SL";
				public const string TIME_DEPOSIT = "TD";
				public const string US_TREASURY_BILL = "USTB";
				public const string WARRANT = "WAR";
				public const string CATS_TIGERS_LIONS = "ZOO";
			}

			// EffectiveTime(168): UTCTIMESTAMP
			public static class EffectiveTime
			{
				public const uint tag = 168;
			}

			// StandInstDbType(169): INT
			public static class StandInstDbType
			{
				public const uint tag = 169;
				public const int OTHER = 0;
				public const int DTC_SID = 1;
				public const int THOMSON_ALERT = 2;
				public const int A_GLOBAL_CUSTODIAN = 3;
			}

			// StandInstDbName(170): STRING
			public static class StandInstDbName
			{
				public const uint tag = 170;
			}

			// StandInstDbID(171): STRING
			public static class StandInstDbID
			{
				public const uint tag = 171;
			}

			// SettlDeliveryType(172): INT
			public static class SettlDeliveryType
			{
				public const uint tag = 172;
			}

			// SettlDepositoryCode(173): STRING
			public static class SettlDepositoryCode
			{
				public const uint tag = 173;
			}

			// SettlBrkrCode(174): STRING
			public static class SettlBrkrCode
			{
				public const uint tag = 174;
			}

			// SettlInstCode(175): STRING
			public static class SettlInstCode
			{
				public const uint tag = 175;
			}

			// SecuritySettlAgentName(176): STRING
			public static class SecuritySettlAgentName
			{
				public const uint tag = 176;
			}

			// SecuritySettlAgentCode(177): STRING
			public static class SecuritySettlAgentCode
			{
				public const uint tag = 177;
			}

			// SecuritySettlAgentAcctNum(178): STRING
			public static class SecuritySettlAgentAcctNum
			{
				public const uint tag = 178;
			}

			// SecuritySettlAgentAcctName(179): STRING
			public static class SecuritySettlAgentAcctName
			{
				public const uint tag = 179;
			}

			// SecuritySettlAgentContactName(180): STRING
			public static class SecuritySettlAgentContactName
			{
				public const uint tag = 180;
			}

			// SecuritySettlAgentContactPhone(181): STRING
			public static class SecuritySettlAgentContactPhone
			{
				public const uint tag = 181;
			}

			// CashSettlAgentName(182): STRING
			public static class CashSettlAgentName
			{
				public const uint tag = 182;
			}

			// CashSettlAgentCode(183): STRING
			public static class CashSettlAgentCode
			{
				public const uint tag = 183;
			}

			// CashSettlAgentAcctNum(184): STRING
			public static class CashSettlAgentAcctNum
			{
				public const uint tag = 184;
			}

			// CashSettlAgentAcctName(185): STRING
			public static class CashSettlAgentAcctName
			{
				public const uint tag = 185;
			}

			// CashSettlAgentContactName(186): STRING
			public static class CashSettlAgentContactName
			{
				public const uint tag = 186;
			}

			// CashSettlAgentContactPhone(187): STRING
			public static class CashSettlAgentContactPhone
			{
				public const uint tag = 187;
			}

			// BidSpotRate(188): PRICE
			public static class BidSpotRate
			{
				public const uint tag = 188;
			}

			// BidForwardPoints(189): PRICEOFFSET
			public static class BidForwardPoints
			{
				public const uint tag = 189;
			}

			// OfferSpotRate(190): PRICE
			public static class OfferSpotRate
			{
				public const uint tag = 190;
			}

			// OfferForwardPoints(191): PRICEOFFSET
			public static class OfferForwardPoints
			{
				public const uint tag = 191;
			}

			// OrderQty2(192): QTY
			public static class OrderQty2
			{
				public const uint tag = 192;
			}

			// FutSettDate2(193): LOCALMKTDATE
			public static class FutSettDate2
			{
				public const uint tag = 193;
			}

			// LastSpotRate(194): PRICE
			public static class LastSpotRate
			{
				public const uint tag = 194;
			}

			// LastForwardPoints(195): PRICEOFFSET
			public static class LastForwardPoints
			{
				public const uint tag = 195;
			}

			// AllocLinkID(196): STRING
			public static class AllocLinkID
			{
				public const uint tag = 196;
			}

			// AllocLinkType(197): INT
			public static class AllocLinkType
			{
				public const uint tag = 197;
				public const int F_X_NETTING = 0;
				public const int F_X_SWAP = 1;
			}

			// SecondaryOrderID(198): STRING
			public static class SecondaryOrderID
			{
				public const uint tag = 198;
			}

			// NoIOIQualifiers(199): INT
			public static class NoIOIQualifiers
			{
				public const uint tag = 199;
			}

			// MaturityMonthYear(200): MONTHYEAR
			public static class MaturityMonthYear
			{
				public const uint tag = 200;
			}

			// PutOrCall(201): INT
			public static class PutOrCall
			{
				public const uint tag = 201;
				public const int PUT = 0;
				public const int CALL = 1;
			}

			// StrikePrice(202): PRICE
			public static class StrikePrice
			{
				public const uint tag = 202;
			}

			// CoveredOrUncovered(203): INT
			public static class CoveredOrUncovered
			{
				public const uint tag = 203;
				public const int COVERED = 0;
				public const int UNCOVERED = 1;
			}

			// CustomerOrFirm(204): INT
			public static class CustomerOrFirm
			{
				public const uint tag = 204;
				public const int CUSTOMER = 0;
				public const int FIRM = 1;
			}

			// MaturityDay(205): DAYOFMONTH
			public static class MaturityDay
			{
				public const uint tag = 205;
			}

			// OptAttribute(206): CHAR
			public static class OptAttribute
			{
				public const uint tag = 206;
			}

			// SecurityExchange(207): EXCHANGE
			public static class SecurityExchange
			{
				public const uint tag = 207;
			}

			// NotifyBrokerOfCredit(208): BOOLEAN
			public static class NotifyBrokerOfCredit
			{
				public const uint tag = 208;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// AllocHandlInst(209): INT
			public static class AllocHandlInst
			{
				public const uint tag = 209;
				public const int MATCH = 1;
				public const int FORWARD = 2;
				public const int FORWARD_AND_MATCH = 3;
			}

			// MaxShow(210): QTY
			public static class MaxShow
			{
				public const uint tag = 210;
			}

			// PegDifference(211): PRICEOFFSET
			public static class PegDifference
			{
				public const uint tag = 211;
			}

			// XmlDataLen(212): LENGTH
			public static class XmlDataLen
			{
				public const uint tag = 212;
			}

			// XmlData(213): DATA
			public static class XmlData
			{
				public const uint tag = 213;
			}

			// SettlInstRefID(214): STRING
			public static class SettlInstRefID
			{
				public const uint tag = 214;
			}

			// NoRoutingIDs(215): INT
			public static class NoRoutingIDs
			{
				public const uint tag = 215;
			}

			// RoutingType(216): INT
			public static class RoutingType
			{
				public const uint tag = 216;
				public const int TARGET_FIRM = 1;
				public const int TARGET_LIST = 2;
				public const int BLOCK_FIRM = 3;
				public const int BLOCK_LIST = 4;
			}

			// RoutingID(217): STRING
			public static class RoutingID
			{
				public const uint tag = 217;
			}

			// SpreadToBenchmark(218): PRICEOFFSET
			public static class SpreadToBenchmark
			{
				public const uint tag = 218;
			}

			// Benchmark(219): CHAR
			public static class Benchmark
			{
				public const uint tag = 219;
				public const char CURVE = '1';
				public const char _5_YR = '2';
				public const char OLD_5 = '3';
				public const char _10_YR = '4';
				public const char OLD_10 = '5';
				public const char _30_YR = '6';
				public const char OLD_30 = '7';
				public const char _3_MO_LIBOR = '8';
				public const char _6_MO_LIBOR = '9';
			}

			// CouponRate(223): FLOAT
			public static class CouponRate
			{
				public const uint tag = 223;
			}

			// ContractMultiplier(231): FLOAT
			public static class ContractMultiplier
			{
				public const uint tag = 231;
			}

			// MDReqID(262): STRING
			public static class MDReqID
			{
				public const uint tag = 262;
			}

			// SubscriptionRequestType(263): CHAR
			public static class SubscriptionRequestType
			{
				public const uint tag = 263;
				public const char SNAPSHOT = '0';
				public const char SNAPSHOT_PLUS_UPDATES = '1';
				public const char DISABLE_PREVIOUS_SNAPSHOT_PLUS_UPDATE_REQUEST = '2';
			}

			// MarketDepth(264): INT
			public static class MarketDepth
			{
				public const uint tag = 264;
			}

			// MDUpdateType(265): INT
			public static class MDUpdateType
			{
				public const uint tag = 265;
				public const int FULL_REFRESH = 0;
				public const int INCREMENTAL_REFRESH = 1;
			}

			// AggregatedBook(266): BOOLEAN
			public static class AggregatedBook
			{
				public const uint tag = 266;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// NoMDEntryTypes(267): INT
			public static class NoMDEntryTypes
			{
				public const uint tag = 267;
			}

			// NoMDEntries(268): INT
			public static class NoMDEntries
			{
				public const uint tag = 268;
			}

			// MDEntryType(269): CHAR
			public static class MDEntryType
			{
				public const uint tag = 269;
				public const char BID = '0';
				public const char OFFER = '1';
				public const char TRADE = '2';
				public const char INDEX_VALUE = '3';
				public const char OPENING_PRICE = '4';
				public const char CLOSING_PRICE = '5';
				public const char SETTLEMENT_PRICE = '6';
				public const char TRADING_SESSION_HIGH_PRICE = '7';
				public const char TRADING_SESSION_LOW_PRICE = '8';
				public const char TRADING_SESSION_VWAP_PRICE = '9';
			}

			// MDEntryPx(270): PRICE
			public static class MDEntryPx
			{
				public const uint tag = 270;
			}

			// MDEntrySize(271): QTY
			public static class MDEntrySize
			{
				public const uint tag = 271;
			}

			// MDEntryDate(272): UTCDATE
			public static class MDEntryDate
			{
				public const uint tag = 272;
			}

			// MDEntryTime(273): UTCTIMEONLY
			public static class MDEntryTime
			{
				public const uint tag = 273;
			}

			// TickDirection(274): CHAR
			public static class TickDirection
			{
				public const uint tag = 274;
				public const char PLUS_TICK = '0';
				public const char ZERO_PLUS_TICK = '1';
				public const char MINUS_TICK = '2';
				public const char ZERO_MINUS_TICK = '3';
			}

			// MDMkt(275): EXCHANGE
			public static class MDMkt
			{
				public const uint tag = 275;
			}

			// QuoteCondition(276): MULTIPLEVALUESTRING
			public static class QuoteCondition
			{
				public const uint tag = 276;
				public const string OPEN = "A";
				public const string CLOSED = "B";
				public const string EXCHANGE_BEST = "C";
				public const string CONSOLIDATED_BEST = "D";
				public const string LOCKED = "E";
				public const string CROSSED = "F";
				public const string DEPTH = "G";
				public const string FAST_TRADING = "H";
				public const string NON_FIRM = "I";
			}

			// TradeCondition(277): MULTIPLEVALUESTRING
			public static class TradeCondition
			{
				public const uint tag = 277;
				public const string CASH = "A";
				public const string AVERAGE_PRICE_TRADE = "B";
				public const string CASH_TRADE = "C";
				public const string NEXT_DAY = "D";
				public const string OPENING = "E";
				public const string INTRADAY_TRADE_DETAIL = "F";
				public const string RULE_127_TRADE = "G";
				public const string RULE_155_TRADE = "H";
				public const string SOLD_LAST = "I";
				public const string NEXT_DAY_TRADE = "J";
				public const string OPENED = "K";
				public const string SELLER = "L";
				public const string SOLD = "M";
				public const string STOPPED_STOCK = "N";
			}

			// MDEntryID(278): STRING
			public static class MDEntryID
			{
				public const uint tag = 278;
			}

			// MDUpdateAction(279): CHAR
			public static class MDUpdateAction
			{
				public const uint tag = 279;
				public const char NEW = '0';
				public const char CHANGE = '1';
				public const char DELETE = '2';
			}

			// MDEntryRefID(280): STRING
			public static class MDEntryRefID
			{
				public const uint tag = 280;
			}

			// MDReqRejReason(281): CHAR
			public static class MDReqRejReason
			{
				public const uint tag = 281;
				public const char UNKNOWN_SYMBOL = '0';
				public const char DUPLICATE_MDREQID = '1';
				public const char INSUFFICIENT_BANDWIDTH = '2';
				public const char INSUFFICIENT_PERMISSIONS = '3';
				public const char UNSUPPORTED_SUBSCRIPTIONREQUESTTYPE = '4';
				public const char UNSUPPORTED_MARKETDEPTH = '5';
				public const char UNSUPPORTED_MDUPDATETYPE = '6';
				public const char UNSUPPORTED_AGGREGATEDBOOK = '7';
				public const char UNSUPPORTED_MDENTRYTYPE = '8';
			}

			// MDEntryOriginator(282): STRING
			public static class MDEntryOriginator
			{
				public const uint tag = 282;
			}

			// LocationID(283): STRING
			public static class LocationID
			{
				public const uint tag = 283;
			}

			// DeskID(284): STRING
			public static class DeskID
			{
				public const uint tag = 284;
			}

			// DeleteReason(285): CHAR
			public static class DeleteReason
			{
				public const uint tag = 285;
				public const char CANCELATION = '0';
				public const char ERROR = '1';
			}

			// OpenCloseSettleFlag(286): CHAR
			public static class OpenCloseSettleFlag
			{
				public const uint tag = 286;
				public const char DAILY_OPEN = '0';
				public const char SESSION_OPEN = '1';
				public const char DELIVERY_SETTLEMENT_PRICE = '2';
			}

			// SellerDays(287): INT
			public static class SellerDays
			{
				public const uint tag = 287;
			}

			// MDEntryBuyer(288): STRING
			public static class MDEntryBuyer
			{
				public const uint tag = 288;
			}

			// MDEntrySeller(289): STRING
			public static class MDEntrySeller
			{
				public const uint tag = 289;
			}

			// MDEntryPositionNo(290): INT
			public static class MDEntryPositionNo
			{
				public const uint tag = 290;
			}

			// FinancialStatus(291): CHAR
			public static class FinancialStatus
			{
				public const uint tag = 291;
				public const char BANKRUPT = '1';
			}

			// CorporateAction(292): CHAR
			public static class CorporateAction
			{
				public const uint tag = 292;
				public const char EX_DIVIDEND = 'A';
				public const char EX_DISTRIBUTION = 'B';
				public const char EX_RIGHTS = 'C';
				public const char NEW = 'D';
				public const char EX_INTEREST = 'E';
			}

			// DefBidSize(293): QTY
			public static class DefBidSize
			{
				public const uint tag = 293;
			}

			// DefOfferSize(294): QTY
			public static class DefOfferSize
			{
				public const uint tag = 294;
			}

			// NoQuoteEntries(295): INT
			public static class NoQuoteEntries
			{
				public const uint tag = 295;
			}

			// NoQuoteSets(296): INT
			public static class NoQuoteSets
			{
				public const uint tag = 296;
			}

			// QuoteAckStatus(297): INT
			public static class QuoteAckStatus
			{
				public const uint tag = 297;
				public const int ACCEPTED = 0;
				public const int CANCELED_FOR_SYMBOL = 1;
				public const int CANCELED_FOR_SECURITY_TYPE = 2;
				public const int CANCELED_FOR_UNDERLYING = 3;
				public const int CANCELED_ALL = 4;
				public const int REJECTED = 5;
			}

			// QuoteCancelType(298): INT
			public static class QuoteCancelType
			{
				public const uint tag = 298;
				public const int CANCEL_FOR_SYMBOL = 1;
				public const int CANCEL_FOR_SECURITY_TYPE = 2;
				public const int CANCEL_FOR_UNDERLYING_SYMBOL = 3;
				public const int CANCEL_FOR_ALL_QUOTES = 4;
			}

			// QuoteEntryID(299): STRING
			public static class QuoteEntryID
			{
				public const uint tag = 299;
			}

			// QuoteRejectReason(300): INT
			public static class QuoteRejectReason
			{
				public const uint tag = 300;
				public const int UNKNOWN_SYMBOL = 1;
				public const int EXCHANGE = 2;
				public const int QUOTE_REQUEST_EXCEEDS_LIMIT = 3;
				public const int TOO_LATE_TO_ENTER = 4;
				public const int UNKNOWN_QUOTE = 5;
				public const int DUPLICATE_QUOTE = 6;
				public const int INVALID_BID_ASK_SPREAD = 7;
				public const int INVALID_PRICE = 8;
				public const int NOT_AUTHORIZED_TO_QUOTE_SECURITY = 9;
			}

			// QuoteResponseLevel(301): INT
			public static class QuoteResponseLevel
			{
				public const uint tag = 301;
				public const int NO_ACKNOWLEDGEMENT = 0;
				public const int ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES = 1;
				public const int ACKNOWLEDGE_EACH_QUOTE_MESSAGES = 2;
			}

			// QuoteSetID(302): STRING
			public static class QuoteSetID
			{
				public const uint tag = 302;
			}

			// QuoteRequestType(303): INT
			public static class QuoteRequestType
			{
				public const uint tag = 303;
				public const int MANUAL = 1;
				public const int AUTOMATIC = 2;
			}

			// TotQuoteEntries(304): INT
			public static class TotQuoteEntries
			{
				public const uint tag = 304;
			}

			// UnderlyingIDSource(305): STRING
			public static class UnderlyingIDSource
			{
				public const uint tag = 305;
			}

			// UnderlyingIssuer(306): STRING
			public static class UnderlyingIssuer
			{
				public const uint tag = 306;
			}

			// UnderlyingSecurityDesc(307): STRING
			public static class UnderlyingSecurityDesc
			{
				public const uint tag = 307;
			}

			// UnderlyingSecurityExchange(308): EXCHANGE
			public static class UnderlyingSecurityExchange
			{
				public const uint tag = 308;
			}

			// UnderlyingSecurityID(309): STRING
			public static class UnderlyingSecurityID
			{
				public const uint tag = 309;
			}

			// UnderlyingSecurityType(310): STRING
			public static class UnderlyingSecurityType
			{
				public const uint tag = 310;
			}

			// UnderlyingSymbol(311): STRING
			public static class UnderlyingSymbol
			{
				public const uint tag = 311;
			}

			// UnderlyingSymbolSfx(312): STRING
			public static class UnderlyingSymbolSfx
			{
				public const uint tag = 312;
			}

			// UnderlyingMaturityMonthYear(313): MONTHYEAR
			public static class UnderlyingMaturityMonthYear
			{
				public const uint tag = 313;
			}

			// UnderlyingMaturityDay(314): DAYOFMONTH
			public static class UnderlyingMaturityDay
			{
				public const uint tag = 314;
			}

			// UnderlyingPutOrCall(315): INT
			public static class UnderlyingPutOrCall
			{
				public const uint tag = 315;
			}

			// UnderlyingStrikePrice(316): PRICE
			public static class UnderlyingStrikePrice
			{
				public const uint tag = 316;
			}

			// UnderlyingOptAttribute(317): CHAR
			public static class UnderlyingOptAttribute
			{
				public const uint tag = 317;
			}

			// UnderlyingCurrency(318): CURRENCY
			public static class UnderlyingCurrency
			{
				public const uint tag = 318;
			}

			// RatioQty(319): QUANTITY
			public static class RatioQty
			{
				public const uint tag = 319;
			}

			// SecurityReqID(320): STRING
			public static class SecurityReqID
			{
				public const uint tag = 320;
			}

			// SecurityRequestType(321): INT
			public static class SecurityRequestType
			{
				public const uint tag = 321;
				public const int REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS = 0;
				public const int REQUEST_SECURITY_IDENTITY_FOR_THE_SPECIFICATIONS_PROVIDED = 1;
				public const int REQUEST_LIST_SECURITY_TYPES = 2;
				public const int REQUEST_LIST_SECURITIES = 3;
			}

			// SecurityResponseID(322): STRING
			public static class SecurityResponseID
			{
				public const uint tag = 322;
			}

			// SecurityResponseType(323): INT
			public static class SecurityResponseType
			{
				public const uint tag = 323;
				public const int ACCEPT_SECURITY_PROPOSAL_AS_IS = 1;
				public const int ACCEPT_SECURITY_PROPOSAL_WITH_REVISIONS_AS_INDICATED_IN_THE_MESSAGE = 2;
				public const int LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST = 3;
				public const int LIST_OF_SECURITIES_RETURNED_PER_REQUEST = 4;
				public const int REJECT_SECURITY_PROPOSAL = 5;
				public const int CAN_NOT_MATCH_SELECTION_CRITERIA = 6;
			}

			// SecurityStatusReqID(324): STRING
			public static class SecurityStatusReqID
			{
				public const uint tag = 324;
			}

			// UnsolicitedIndicator(325): BOOLEAN
			public static class UnsolicitedIndicator
			{
				public const uint tag = 325;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// SecurityTradingStatus(326): INT
			public static class SecurityTradingStatus
			{
				public const uint tag = 326;
				public const int OPENING_DELAY = 1;
				public const int MARKET_ON_CLOSE_IMBALANCE_SELL = 10;
				public const int _11 = 11;
				public const int NO_MARKET_IMBALANCE = 12;
				public const int NO_MARKET_ON_CLOSE_IMBALANCE = 13;
				public const int ITS_PRE_OPENING = 14;
				public const int NEW_PRICE_INDICATION = 15;
				public const int TRADE_DISSEMINATION_TIME = 16;
				public const int READY_TO_TRADE = 17;
				public const int NOT_AVAILABLE_FOR_TRADING = 18;
				public const int NOT_TRADED_ON_THIS_MARKET = 19;
				public const int TRADING_HALT = 2;
				public const int UNKNOWN_OR_INVALID = 20;
				public const int RESUME = 3;
				public const int NO_OPEN_NO_RESUME = 4;
				public const int PRICE_INDICATION = 5;
				public const int TRADING_RANGE_INDICATION = 6;
				public const int MARKET_IMBALANCE_BUY = 7;
				public const int MARKET_IMBALANCE_SELL = 8;
				public const int MARKET_ON_CLOSE_IMBALANCE_BUY = 9;
			}

			// HaltReasonChar(327): CHAR
			public static class HaltReasonChar
			{
				public const uint tag = 327;
				public const char NEWS_DISSEMINATION = 'D';
				public const char ORDER_INFLUX = 'E';
				public const char ORDER_IMBALANCE = 'I';
				public const char ADDITIONAL_INFORMATION = 'M';
				public const char NEWS_PENDING = 'P';
				public const char EQUIPMENT_CHANGEOVER = 'X';
			}

			// InViewOfCommon(328): BOOLEAN
			public static class InViewOfCommon
			{
				public const uint tag = 328;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// DueToRelated(329): BOOLEAN
			public static class DueToRelated
			{
				public const uint tag = 329;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// BuyVolume(330): QTY
			public static class BuyVolume
			{
				public const uint tag = 330;
			}

			// SellVolume(331): QTY
			public static class SellVolume
			{
				public const uint tag = 331;
			}

			// HighPx(332): PRICE
			public static class HighPx
			{
				public const uint tag = 332;
			}

			// LowPx(333): PRICE
			public static class LowPx
			{
				public const uint tag = 333;
			}

			// Adjustment(334): INT
			public static class Adjustment
			{
				public const uint tag = 334;
				public const int CANCEL = 1;
				public const int ERROR = 2;
				public const int CORRECTION = 3;
			}

			// TradSesReqID(335): STRING
			public static class TradSesReqID
			{
				public const uint tag = 335;
			}

			// TradingSessionID(336): STRING
			public static class TradingSessionID
			{
				public const uint tag = 336;
			}

			// ContraTrader(337): STRING
			public static class ContraTrader
			{
				public const uint tag = 337;
			}

			// TradSesMethod(338): INT
			public static class TradSesMethod
			{
				public const uint tag = 338;
				public const int ELECTRONIC = 1;
				public const int OPEN_OUTCRY = 2;
				public const int TWO_PARTY = 3;
			}

			// TradSesMode(339): INT
			public static class TradSesMode
			{
				public const uint tag = 339;
				public const int TESTING = 1;
				public const int SIMULATED = 2;
				public const int PRODUCTION = 3;
			}

			// TradSesStatus(340): INT
			public static class TradSesStatus
			{
				public const uint tag = 340;
				public const int HALTED = 1;
				public const int OPEN = 2;
				public const int CLOSED = 3;
				public const int PRE_OPEN = 4;
				public const int PRE_CLOSE = 5;
			}

			// TradSesStartTime(341): UTCTIMESTAMP
			public static class TradSesStartTime
			{
				public const uint tag = 341;
			}

			// TradSesOpenTime(342): UTCTIMESTAMP
			public static class TradSesOpenTime
			{
				public const uint tag = 342;
			}

			// TradSesPreCloseTime(343): UTCTIMESTAMP
			public static class TradSesPreCloseTime
			{
				public const uint tag = 343;
			}

			// TradSesCloseTime(344): UTCTIMESTAMP
			public static class TradSesCloseTime
			{
				public const uint tag = 344;
			}

			// TradSesEndTime(345): UTCTIMESTAMP
			public static class TradSesEndTime
			{
				public const uint tag = 345;
			}

			// NumberOfOrders(346): INT
			public static class NumberOfOrders
			{
				public const uint tag = 346;
			}

			// MessageEncoding(347): STRING
			public static class MessageEncoding
			{
				public const uint tag = 347;
				public const string EUC_JP = "EUC-JP";
				public const string ISO_2022_JP = "ISO-2022-JP";
				public const string SHIFT_JIS = "SHIFT_JIS";
				public const string UTF_8 = "UTF-8";
			}

			// EncodedIssuerLen(348): LENGTH
			public static class EncodedIssuerLen
			{
				public const uint tag = 348;
			}

			// EncodedIssuer(349): DATA
			public static class EncodedIssuer
			{
				public const uint tag = 349;
			}

			// EncodedSecurityDescLen(350): LENGTH
			public static class EncodedSecurityDescLen
			{
				public const uint tag = 350;
			}

			// EncodedSecurityDesc(351): DATA
			public static class EncodedSecurityDesc
			{
				public const uint tag = 351;
			}

			// EncodedListExecInstLen(352): LENGTH
			public static class EncodedListExecInstLen
			{
				public const uint tag = 352;
			}

			// EncodedListExecInst(353): DATA
			public static class EncodedListExecInst
			{
				public const uint tag = 353;
			}

			// EncodedTextLen(354): LENGTH
			public static class EncodedTextLen
			{
				public const uint tag = 354;
			}

			// EncodedText(355): DATA
			public static class EncodedText
			{
				public const uint tag = 355;
			}

			// EncodedSubjectLen(356): LENGTH
			public static class EncodedSubjectLen
			{
				public const uint tag = 356;
			}

			// EncodedSubject(357): DATA
			public static class EncodedSubject
			{
				public const uint tag = 357;
			}

			// EncodedHeadlineLen(358): LENGTH
			public static class EncodedHeadlineLen
			{
				public const uint tag = 358;
			}

			// EncodedHeadline(359): DATA
			public static class EncodedHeadline
			{
				public const uint tag = 359;
			}

			// EncodedAllocTextLen(360): LENGTH
			public static class EncodedAllocTextLen
			{
				public const uint tag = 360;
			}

			// EncodedAllocText(361): DATA
			public static class EncodedAllocText
			{
				public const uint tag = 361;
			}

			// EncodedUnderlyingIssuerLen(362): LENGTH
			public static class EncodedUnderlyingIssuerLen
			{
				public const uint tag = 362;
			}

			// EncodedUnderlyingIssuer(363): DATA
			public static class EncodedUnderlyingIssuer
			{
				public const uint tag = 363;
			}

			// EncodedUnderlyingSecurityDescLen(364): LENGTH
			public static class EncodedUnderlyingSecurityDescLen
			{
				public const uint tag = 364;
			}

			// EncodedUnderlyingSecurityDesc(365): DATA
			public static class EncodedUnderlyingSecurityDesc
			{
				public const uint tag = 365;
			}

			// AllocPrice(366): PRICE
			public static class AllocPrice
			{
				public const uint tag = 366;
			}

			// QuoteSetValidUntilTime(367): UTCTIMESTAMP
			public static class QuoteSetValidUntilTime
			{
				public const uint tag = 367;
			}

			// QuoteEntryRejectReason(368): INT
			public static class QuoteEntryRejectReason
			{
				public const uint tag = 368;
				public const int UNKNOWN_SYMBOL = 1;
				public const int EXCHANGE = 2;
				public const int QUOTE_EXCEEDS_LIMIT = 3;
				public const int TOO_LATE_TO_ENTER = 4;
				public const int UNKNOWN_QUOTE = 5;
				public const int DUPLICATE_QUOTE = 6;
				public const int INVALID_BID_ASK_SPREAD = 7;
				public const int INVALID_PRICE = 8;
				public const int NOT_AUTHORIZED_TO_QUOTE_SECURITY = 9;
			}

			// LastMsgSeqNumProcessed(369): INT
			public static class LastMsgSeqNumProcessed
			{
				public const uint tag = 369;
			}

			// OnBehalfOfSendingTime(370): UTCTIMESTAMP
			public static class OnBehalfOfSendingTime
			{
				public const uint tag = 370;
			}

			// RefTagID(371): INT
			public static class RefTagID
			{
				public const uint tag = 371;
			}

			// RefMsgType(372): STRING
			public static class RefMsgType
			{
				public const uint tag = 372;
			}

			// SessionRejectReason(373): INT
			public static class SessionRejectReason
			{
				public const uint tag = 373;
				public const int INVALID_TAG_NUMBER = 0;
				public const int REQUIRED_TAG_MISSING = 1;
				public const int SENDINGTIME_ACCURACY_PROBLEM = 10;
				public const int INVALID_MSGTYPE = 11;
				public const int TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE = 2;
				public const int UNDEFINED_TAG = 3;
				public const int TAG_SPECIFIED_WITHOUT_A_VALUE = 4;
				public const int VALUE_IS_INCORRECT = 5;
				public const int INCORRECT_DATA_FORMAT_FOR_VALUE = 6;
				public const int DECRYPTION_PROBLEM = 7;
				public const int SIGNATURE_PROBLEM = 8;
				public const int COMPID_PROBLEM = 9;
			}

			// BidRequestTransType(374): CHAR
			public static class BidRequestTransType
			{
				public const uint tag = 374;
				public const char CANCEL = 'C';
				public const char NO = 'N';
			}

			// ContraBroker(375): STRING
			public static class ContraBroker
			{
				public const uint tag = 375;
			}

			// ComplianceID(376): STRING
			public static class ComplianceID
			{
				public const uint tag = 376;
			}

			// SolicitedFlag(377): BOOLEAN
			public static class SolicitedFlag
			{
				public const uint tag = 377;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// ExecRestatementReason(378): INT
			public static class ExecRestatementReason
			{
				public const uint tag = 378;
				public const int GT_CORPORATE_ACTION = 0;
				public const int GT_RENEWAL = 1;
				public const int VERBAL_CHANGE = 2;
				public const int REPRICING_OF_ORDER = 3;
				public const int BROKER_OPTION = 4;
				public const int PARTIAL_DECLINE_OF_ORDERQTY = 5;
			}

			// BusinessRejectRefID(379): STRING
			public static class BusinessRejectRefID
			{
				public const uint tag = 379;
			}

			// BusinessRejectReason(380): INT
			public static class BusinessRejectReason
			{
				public const uint tag = 380;
				public const int OTHER = 0;
				public const int UNKOWN_ID = 1;
				public const int UNKNOWN_SECURITY = 2;
				public const int UNSUPPORTED_MESSAGE_TYPE = 3;
				public const int APPLICATION_NOT_AVAILABLE = 4;
				public const int CONDITIONALLY_REQUIRED_FIELD_MISSING = 5;
			}

			// GrossTradeAmt(381): AMT
			public static class GrossTradeAmt
			{
				public const uint tag = 381;
			}

			// NoContraBrokers(382): INT
			public static class NoContraBrokers
			{
				public const uint tag = 382;
			}

			// MaxMessageSize(383): INT
			public static class MaxMessageSize
			{
				public const uint tag = 383;
			}

			// NoMsgTypes(384): INT
			public static class NoMsgTypes
			{
				public const uint tag = 384;
			}

			// MsgDirection(385): CHAR
			public static class MsgDirection
			{
				public const uint tag = 385;
				public const char RECEIVE = 'R';
				public const char SEND = 'S';
			}

			// NoTradingSessions(386): INT
			public static class NoTradingSessions
			{
				public const uint tag = 386;
			}

			// TotalVolumeTraded(387): QTY
			public static class TotalVolumeTraded
			{
				public const uint tag = 387;
			}

			// DiscretionInst(388): CHAR
			public static class DiscretionInst
			{
				public const uint tag = 388;
				public const char RELATED_TO_DISPLAYED_PRICE = '0';
				public const char RELATED_TO_MARKET_PRICE = '1';
				public const char RELATED_TO_PRIMARY_PRICE = '2';
				public const char RELATED_TO_LOCAL_PRIMARY_PRICE = '3';
				public const char RELATED_TO_MIDPOINT_PRICE = '4';
				public const char RELATED_TO_LAST_TRADE_PRICE = '5';
			}

			// DiscretionOffset(389): PRICEOFFSET
			public static class DiscretionOffset
			{
				public const uint tag = 389;
			}

			// BidID(390): STRING
			public static class BidID
			{
				public const uint tag = 390;
			}

			// ClientBidID(391): STRING
			public static class ClientBidID
			{
				public const uint tag = 391;
			}

			// ListName(392): STRING
			public static class ListName
			{
				public const uint tag = 392;
			}

			// TotalNumSecurities(393): INT
			public static class TotalNumSecurities
			{
				public const uint tag = 393;
			}

			// BidType(394): INT
			public static class BidType
			{
				public const uint tag = 394;
			}

			// NumTickets(395): INT
			public static class NumTickets
			{
				public const uint tag = 395;
			}

			// SideValue1(396): AMT
			public static class SideValue1
			{
				public const uint tag = 396;
			}

			// SideValue2(397): AMT
			public static class SideValue2
			{
				public const uint tag = 397;
			}

			// NoBidDescriptors(398): INT
			public static class NoBidDescriptors
			{
				public const uint tag = 398;
			}

			// BidDescriptorType(399): INT
			public static class BidDescriptorType
			{
				public const uint tag = 399;
			}

			// BidDescriptor(400): STRING
			public static class BidDescriptor
			{
				public const uint tag = 400;
			}

			// SideValueInd(401): INT
			public static class SideValueInd
			{
				public const uint tag = 401;
			}

			// LiquidityPctLow(402): FLOAT
			public static class LiquidityPctLow
			{
				public const uint tag = 402;
			}

			// LiquidityPctHigh(403): FLOAT
			public static class LiquidityPctHigh
			{
				public const uint tag = 403;
			}

			// LiquidityValue(404): AMT
			public static class LiquidityValue
			{
				public const uint tag = 404;
			}

			// EFPTrackingError(405): FLOAT
			public static class EFPTrackingError
			{
				public const uint tag = 405;
			}

			// FairValue(406): AMT
			public static class FairValue
			{
				public const uint tag = 406;
			}

			// OutsideIndexPct(407): FLOAT
			public static class OutsideIndexPct
			{
				public const uint tag = 407;
			}

			// ValueOfFutures(408): AMT
			public static class ValueOfFutures
			{
				public const uint tag = 408;
			}

			// LiquidityIndType(409): INT
			public static class LiquidityIndType
			{
				public const uint tag = 409;
				public const int _5_DAY_MOVING_AVERAGE = 1;
				public const int _20_DAY_MOVING_AVERAGE = 2;
				public const int NORMAL_MARKET_SIZE = 3;
				public const int OTHER = 4;
			}

			// WtAverageLiquidity(410): FLOAT
			public static class WtAverageLiquidity
			{
				public const uint tag = 410;
			}

			// ExchangeForPhysical(411): BOOLEAN
			public static class ExchangeForPhysical
			{
				public const uint tag = 411;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// OutMainCntryUIndex(412): AMT
			public static class OutMainCntryUIndex
			{
				public const uint tag = 412;
			}

			// CrossPercent(413): FLOAT
			public static class CrossPercent
			{
				public const uint tag = 413;
			}

			// ProgRptReqs(414): INT
			public static class ProgRptReqs
			{
				public const uint tag = 414;
				public const int BUYSIDE_EXPLICITLY_REQUESTS_STATUS_USING_STATUSREQUEST = 1;
				public const int SELLSIDE_PERIODICALLY_SENDS_STATUS_USING_LISTSTATUS_PERIOD_OPTIONALLY_SPECIFIED_IN_PROGRESSPERIOD = 2;
				public const int REAL_TIME_EXECUTION_REPORTS = 3;
			}

			// ProgPeriodInterval(415): INT
			public static class ProgPeriodInterval
			{
				public const uint tag = 415;
			}

			// IncTaxInd(416): INT
			public static class IncTaxInd
			{
				public const uint tag = 416;
				public const int NET = 1;
				public const int GROSS = 2;
			}

			// NumBidders(417): INT
			public static class NumBidders
			{
				public const uint tag = 417;
			}

			// TradeType(418): CHAR
			public static class TradeType
			{
				public const uint tag = 418;
				public const char AGENCY = 'A';
				public const char VWAP_GUARANTEE = 'G';
				public const char GUARANTEED_CLOSE = 'J';
				public const char RISK_TRADE = 'R';
			}

			// BasisPxType(419): CHAR
			public static class BasisPxType
			{
				public const uint tag = 419;
				public const char CLOSING_PRICE_AT_MORNING_SESSION = '2';
				public const char CLOSING_PRICE = '3';
				public const char CURRENT_PRICE = '4';
				public const char SQ = '5';
				public const char VWAP_THROUGH_A_DAY = '6';
				public const char VWAP_THROUGH_A_MORNING_SESSION = '7';
				public const char VWAP_THROUGH_AN_AFTERNOON_SESSION = '8';
				public const char VWAP_THROUGH_A_DAY_EXCEPT_YORI = '9';
				public const char VWAP_THROUGH_A_MORNING_SESSION_EXCEPT_YORI = 'A';
				public const char VWAP_THROUGH_AN_AFTERNOON_SESSION_EXCEPT_YORI = 'B';
				public const char STRIKE = 'C';
				public const char OPEN = 'D';
				public const char OTHERS = 'Z';
			}

			// NoBidComponents(420): INT
			public static class NoBidComponents
			{
				public const uint tag = 420;
			}

			// Country(421): STRING
			public static class Country
			{
				public const uint tag = 421;
			}

			// TotNoStrikes(422): INT
			public static class TotNoStrikes
			{
				public const uint tag = 422;
			}

			// PriceType(423): INT
			public static class PriceType
			{
				public const uint tag = 423;
				public const int PERCENTAGE = 1;
				public const int PER_SHARE = 2;
				public const int FIXED_AMOUNT = 3;
			}

			// DayOrderQty(424): QTY
			public static class DayOrderQty
			{
				public const uint tag = 424;
			}

			// DayCumQty(425): QTY
			public static class DayCumQty
			{
				public const uint tag = 425;
			}

			// DayAvgPx(426): PRICE
			public static class DayAvgPx
			{
				public const uint tag = 426;
			}

			// GTBookingInst(427): INT
			public static class GTBookingInst
			{
				public const uint tag = 427;
				public const int BOOK_OUT_ALL_TRADES_ON_DAY_OF_EXECUTION = 0;
				public const int ACCUMULATE_EXECUTIONS_UNTIL_ORDER_IS_FILLED_OR_EXPIRES = 1;
				public const int ACCUMULATE_UNTIL_VERBALLY_NOTIFIED_OTHERWISE = 2;
			}

			// NoStrikes(428): INT
			public static class NoStrikes
			{
				public const uint tag = 428;
			}

			// ListStatusType(429): INT
			public static class ListStatusType
			{
				public const uint tag = 429;
			}

			// NetGrossInd(430): INT
			public static class NetGrossInd
			{
				public const uint tag = 430;
				public const int NET = 1;
				public const int GROSS = 2;
			}

			// ListOrderStatus(431): INT
			public static class ListOrderStatus
			{
				public const uint tag = 431;
			}

			// ExpireDate(432): LOCALMKTDATE
			public static class ExpireDate
			{
				public const uint tag = 432;
			}

			// ListExecInstType(433): CHAR
			public static class ListExecInstType
			{
				public const uint tag = 433;
				public const char IMMEDIATE = '1';
				public const char WAIT_FOR_EXECUTE_INSTRUCTION = '2';
			}

			// CxlRejResponseTo(434): CHAR
			public static class CxlRejResponseTo
			{
				public const uint tag = 434;
				public const char ORDER_CANCEL_REQUEST = '1';
				public const char ORDER_CANCEL_REPLACE_REQUEST = '2';
			}

			// UnderlyingCouponRate(435): FLOAT
			public static class UnderlyingCouponRate
			{
				public const uint tag = 435;
			}

			// UnderlyingContractMultiplier(436): FLOAT
			public static class UnderlyingContractMultiplier
			{
				public const uint tag = 436;
			}

			// ContraTradeQty(437): QTY
			public static class ContraTradeQty
			{
				public const uint tag = 437;
			}

			// ContraTradeTime(438): UTCTIMESTAMP
			public static class ContraTradeTime
			{
				public const uint tag = 438;
			}

			// ClearingFirm(439): STRING
			public static class ClearingFirm
			{
				public const uint tag = 439;
			}

			// ClearingAccount(440): STRING
			public static class ClearingAccount
			{
				public const uint tag = 440;
			}

			// LiquidityNumSecurities(441): INT
			public static class LiquidityNumSecurities
			{
				public const uint tag = 441;
			}

			// MultiLegReportingType(442): CHAR
			public static class MultiLegReportingType
			{
				public const uint tag = 442;
				public const char SINGLE_SECURITY = '1';
				public const char INDIVIDUAL_LEG_OF_A_MULTI_LEG_SECURITY = '2';
				public const char MULTI_LEG_SECURITY = '3';
			}

			// StrikeTime(443): UTCTIMESTAMP
			public static class StrikeTime
			{
				public const uint tag = 443;
			}

			// ListStatusText(444): STRING
			public static class ListStatusText
			{
				public const uint tag = 444;
			}

			// EncodedListStatusTextLen(445): LENGTH
			public static class EncodedListStatusTextLen
			{
				public const uint tag = 445;
			}

			// EncodedListStatusText(446): DATA
			public static class EncodedListStatusText
			{
				public const uint tag = 446;
			}
		}
	}
}
