/*
    ____                      __      ____
   /\  _`\   __             /'_ `\   /\  _`\
   \ \ \L\_\/\_\    __  _  /\ \L\ \  \ \ \L\ \ _ __    ___
    \ \  _\/\/\ \  /\ \/'\ \/_> _ <_  \ \ ,__//\`'__\ / __`\
     \ \ \/  \ \ \ \/>  </   /\ \L\ \  \ \ \/ \ \ \/ /\ \L\ \
      \ \_\   \ \_\ /\_/\_\  \ \____/   \ \_\  \ \_\ \ \____/
       \/_/    \/_/ \//\/_/   \/___/     \/_/   \/_/  \/___/

               Fix8Pro FIX Engine and Framework

Copyright (C) 2010-19 Fix8 Market Technologies Pty Ltd (ABN 29 167 027 198)
All Rights Reserved. [http://www.fix8mt.com] <heretohelp@fix8mt.com>

THIS FILE IS PROPRIETARY AND  CONFIDENTIAL. NO PART OF THIS FILE MAY BE REPRODUCED,  STORED
IN A RETRIEVAL SYSTEM,  OR TRANSMITTED, IN ANY FORM OR ANY MEANS,  ELECTRONIC, PHOTOSTATIC,
RECORDED OR OTHERWISE, WITHOUT THE PRIOR AND  EXPRESS WRITTEN  PERMISSION  OF  FIX8  MARKET
TECHNOLOGIES PTY LTD.
*/

// Autogenerated on 2019-09-03 07:52:51.739607
// /home/sergey/src/f8/fix8pro/compiler/py/f8c/f8c.py --template ufe_java_fields ufe_cpp_fields ufe_cs_fields ufe_py_fields ufe_cpp_messages --output-dir ./generated --schema-dir /home/sergey/src/f8/fix8pro/schema/xml FIX50SP2 FIX42 FIX44 FIX40 FIX41 FIX43 FIX50 FIX50SP1
// DO NOT EDIT!

namespace UFE.UFEedClient
{
	namespace FIX41
	{
		namespace Field
		{

			// Account(1): CHAR
			public static class Account
			{
				public const uint tag = 1;
			}

			// AdvId(2): CHAR
			public static class AdvId
			{
				public const uint tag = 2;
			}

			// AdvRefID(3): CHAR
			public static class AdvRefID
			{
				public const uint tag = 3;
			}

			// AdvSide(4): CHAR
			public static class AdvSide
			{
				public const uint tag = 4;
				public const char BUY = 'B';
				public const char SELL = 'S';
				public const char TRADE = 'T';
				public const char CROSS = 'X';
			}

			// AdvTransType(5): CHAR
			public static class AdvTransType
			{
				public const uint tag = 5;
				public const char CANCEL = 'C';
				public const char NEW = 'N';
				public const char REPLACE = 'R';
			}

			// AvgPx(6): FLOAT
			public static class AvgPx
			{
				public const uint tag = 6;
			}

			// BeginSeqNo(7): INT
			public static class BeginSeqNo
			{
				public const uint tag = 7;
			}

			// BeginString(8): CHAR
			public static class BeginString
			{
				public const uint tag = 8;
			}

			// BodyLength(9): INT
			public static class BodyLength
			{
				public const uint tag = 9;
			}

			// CheckSum(10): CHAR
			public static class CheckSum
			{
				public const uint tag = 10;
			}

			// ClOrdID(11): CHAR
			public static class ClOrdID
			{
				public const uint tag = 11;
			}

			// Commission(12): FLOAT
			public static class Commission
			{
				public const uint tag = 12;
			}

			// CommType(13): CHAR
			public static class CommType
			{
				public const uint tag = 13;
				public const char PER_SHARE = '1';
				public const char PERCENTAGE = '2';
				public const char ABSOLUTE = '3';
			}

			// CumQty(14): INT
			public static class CumQty
			{
				public const uint tag = 14;
			}

			// Currency(15): CHAR
			public static class Currency
			{
				public const uint tag = 15;
			}

			// EndSeqNo(16): INT
			public static class EndSeqNo
			{
				public const uint tag = 16;
			}

			// ExecID(17): CHAR
			public static class ExecID
			{
				public const uint tag = 17;
			}

			// ExecInst(18): CHAR
			public static class ExecInst
			{
				public const uint tag = 18;
				public const char STAY_ON_OFFERSIDE = '0';
				public const char NOT_HELD = '1';
				public const char WORK = '2';
				public const char GO_ALONG = '3';
				public const char OVER_THE_DAY = '4';
				public const char HELD = '5';
				public const char PARTICIPATE_DONT_INITIATE = '6';
				public const char STRICT_SCALE = '7';
				public const char TRY_TO_SCALE = '8';
				public const char STAY_ON_BIDSIDE = '9';
				public const char NO_CROSS = 'A';
				public const char OK_TO_CROSS = 'B';
				public const char CALL_FIRST = 'C';
				public const char PERCENT_OF_VOLUME = 'D';
				public const char DO_NOT_INCREASE = 'E';
				public const char DO_NOT_REDUCE = 'F';
				public const char ALL_OR_NONE = 'G';
				public const char INSTITUTIONS_ONLY = 'I';
				public const char LAST_PEG = 'L';
				public const char MID_PRICE_PEG = 'M';
				public const char NON_NEGOTIABLE = 'N';
				public const char OPENING_PEG = 'O';
				public const char MARKET_PEG = 'P';
				public const char PRIMARY_PEG = 'R';
				public const char SUSPEND = 'S';
				public const char CUSTOMER_DISPLAY_INSTRUCTION = 'U';
				public const char NETTING = 'V';
			}

			// ExecRefID(19): CHAR
			public static class ExecRefID
			{
				public const uint tag = 19;
			}

			// ExecTransType(20): CHAR
			public static class ExecTransType
			{
				public const uint tag = 20;
				public const char NEW = '0';
				public const char CANCEL = '1';
				public const char CORRECT = '2';
				public const char STATUS = '3';
			}

			// HandlInst(21): CHAR
			public static class HandlInst
			{
				public const uint tag = 21;
				public const char AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION = '1';
				public const char AUTOMATED_EXECUTION_ORDER_PUBLIC_BROKER_INTERVENTION_OK = '2';
				public const char MANUAL_ORDER_BEST_EXECUTION = '3';
			}

			// IDSource(22): CHAR
			public static class IDSource
			{
				public const uint tag = 22;
				public const char CUSIP = '1';
				public const char SEDOL = '2';
				public const char QUIK = '3';
				public const char ISIN_NUMBER = '4';
				public const char RIC_CODE = '5';
				public const char ISO_CURRENCY_CODE = '6';
				public const char ISO_COUNTRY_CODE = '7';
			}

			// IOIid(23): CHAR
			public static class IOIid
			{
				public const uint tag = 23;
			}

			// IOIOthSvc(24): CHAR
			public static class IOIOthSvc
			{
				public const uint tag = 24;
				public const char AUTEX = 'A';
				public const char BRIDGE = 'B';
			}

			// IOIQltyInd(25): CHAR
			public static class IOIQltyInd
			{
				public const uint tag = 25;
				public const char HIGH = 'H';
				public const char LOW = 'L';
				public const char MEDIUM = 'M';
			}

			// IOIRefID(26): CHAR
			public static class IOIRefID
			{
				public const uint tag = 26;
			}

			// IOIShares(27): CHAR
			public static class IOIShares
			{
				public const uint tag = 27;
				public const char LARGE = 'L';
				public const char MEDIUM = 'M';
				public const char SMALL = 'S';
			}

			// IOITransType(28): CHAR
			public static class IOITransType
			{
				public const uint tag = 28;
				public const char CANCEL = 'C';
				public const char NEW = 'N';
				public const char REPLACE = 'R';
			}

			// LastCapacity(29): CHAR
			public static class LastCapacity
			{
				public const uint tag = 29;
				public const char AGENT = '1';
				public const char CROSS_AS_AGENT = '2';
				public const char CROSS_AS_PRINCIPAL = '3';
				public const char PRINCIPAL = '4';
			}

			// LastMkt(30): CHAR
			public static class LastMkt
			{
				public const uint tag = 30;
			}

			// LastPx(31): FLOAT
			public static class LastPx
			{
				public const uint tag = 31;
			}

			// LastShares(32): INT
			public static class LastShares
			{
				public const uint tag = 32;
			}

			// LinesOfText(33): INT
			public static class LinesOfText
			{
				public const uint tag = 33;
			}

			// MsgSeqNum(34): INT
			public static class MsgSeqNum
			{
				public const uint tag = 34;
			}

			// MsgType(35): STRING
			public static class MsgType
			{
				public const uint tag = 35;
				public const string HEARTBEAT = "0";
				public const string TEST_REQUEST = "1";
				public const string RESEND_REQUEST = "2";
				public const string REJECT = "3";
				public const string SEQUENCE_RESET = "4";
				public const string LOGOUT = "5";
				public const string INDICATION_OF_INTEREST = "6";
				public const string ADVERTISEMENT = "7";
				public const string EXECUTION_REPORT = "8";
				public const string ORDER_CANCEL_REJECT = "9";
				public const string LOGON = "A";
				public const string NEWS = "B";
				public const string EMAIL = "C";
				public const string ORDER_D = "D";
				public const string ORDER_E = "E";
				public const string ORDER_CANCEL_REQUEST = "F";
				public const string ORDER_CANCEL_REPLACE_REQUEST = "G";
				public const string ORDER_STATUS_REQUEST = "H";
				public const string ALLOCATION = "J";
				public const string LIST_CANCEL_REQUEST = "K";
				public const string LIST_EXECUTE = "L";
				public const string LIST_STATUS_REQUEST = "M";
				public const string LIST_STATUS = "N";
				public const string ALLOCATION_ACK = "P";
				public const string DONT_KNOW_TRADE = "Q";
				public const string QUOTE_REQUEST = "R";
				public const string QUOTE = "S";
				public const string SETTLEMENT_INSTRUCTIONS = "T";
			}

			// NewSeqNo(36): INT
			public static class NewSeqNo
			{
				public const uint tag = 36;
			}

			// OrderID(37): CHAR
			public static class OrderID
			{
				public const uint tag = 37;
			}

			// OrderQty(38): INT
			public static class OrderQty
			{
				public const uint tag = 38;
			}

			// OrdStatus(39): CHAR
			public static class OrdStatus
			{
				public const uint tag = 39;
				public const char NEW = '0';
				public const char PARTIALLY_FILLED = '1';
				public const char FILLED = '2';
				public const char DONE_FOR_DAY = '3';
				public const char CANCELED = '4';
				public const char REPLACED = '5';
				public const char PENDING_CANCEL_REPLACE = '6';
				public const char STOPPED = '7';
				public const char REJECTED = '8';
				public const char SUSPENDED = '9';
				public const char PENDING_NEW = 'A';
				public const char CALCULATED = 'B';
				public const char EXPIRED = 'C';
			}

			// OrdType(40): CHAR
			public static class OrdType
			{
				public const uint tag = 40;
				public const char MARKET = '1';
				public const char LIMIT = '2';
				public const char STOP = '3';
				public const char STOP_LIMIT = '4';
				public const char MARKET_ON_CLOSE = '5';
				public const char WITH_OR_WITHOUT = '6';
				public const char LIMIT_OR_BETTER = '7';
				public const char LIMIT_WITH_OR_WITHOUT = '8';
				public const char ON_BASIS = '9';
				public const char ON_CLOSE = 'A';
				public const char LIMIT_ON_CLOSE = 'B';
				public const char FOREX_C = 'C';
				public const char PREVIOUSLY_QUOTED = 'D';
				public const char PREVIOUSLY_INDICATED = 'E';
				public const char FOREX_F = 'F';
				public const char FOREX_G = 'G';
				public const char FOREX_H = 'H';
				public const char PEGGED = 'P';
			}

			// OrigClOrdID(41): CHAR
			public static class OrigClOrdID
			{
				public const uint tag = 41;
			}

			// OrigTime(42): UTCTIMESTAMP
			public static class OrigTime
			{
				public const uint tag = 42;
			}

			// PossDupFlag(43): CHAR
			public static class PossDupFlag
			{
				public const uint tag = 43;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// Price(44): FLOAT
			public static class Price
			{
				public const uint tag = 44;
			}

			// RefSeqNum(45): INT
			public static class RefSeqNum
			{
				public const uint tag = 45;
			}

			// RelatdSym(46): CHAR
			public static class RelatdSym
			{
				public const uint tag = 46;
			}

			// Rule80A(47): CHAR
			public static class Rule80A
			{
				public const uint tag = 47;
				public const char AGENCY_SINGLE_ORDER = 'A';
				public const char SHORT_EXEMPT_TRANSACTION_B = 'B';
				public const char PROGRAM_ORDER_NON_INDEX_ARB_FOR_MEMBER_FIRM_ORG = 'C';
				public const char PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG = 'D';
				public const char REGISTERED_EQUITY_MARKET_MAKER_TRADES = 'E';
				public const char SHORT_EXEMPT_TRANSACTION_F = 'F';
				public const char SHORT_EXEMPT_TRANSACTION_H = 'H';
				public const char INDIVIDUAL_INVESTOR_SINGLE_ORDER = 'I';
				public const char PROGRAM_ORDER_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER = 'J';
				public const char PROGRAM_ORDER_NON_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER = 'K';
				public const char SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE = 'L';
				public const char PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER = 'M';
				public const char PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_MEMBER = 'N';
				public const char COMPETING_DEALER_TRADES_O = 'O';
				public const char PRINCIPAL = 'P';
				public const char COMPETING_DEALER_TRADES_R = 'R';
				public const char SPECIALIST_TRADES = 'S';
				public const char COMPETING_DEALER_TRADES_T = 'T';
				public const char PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_AGENCY = 'U';
				public const char ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER = 'W';
				public const char SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE = 'X';
				public const char PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_AGENCY = 'Y';
				public const char SHORT_EXEMPT_TRANSACTION_FOR_NON_MEMBER_COMPETING_MARKET_MAKER = 'Z';
			}

			// SecurityID(48): CHAR
			public static class SecurityID
			{
				public const uint tag = 48;
			}

			// SenderCompID(49): CHAR
			public static class SenderCompID
			{
				public const uint tag = 49;
			}

			// SenderSubID(50): CHAR
			public static class SenderSubID
			{
				public const uint tag = 50;
			}

			// SendingDate(51): LOCALMKTDATE
			public static class SendingDate
			{
				public const uint tag = 51;
			}

			// SendingTime(52): UTCTIMESTAMP
			public static class SendingTime
			{
				public const uint tag = 52;
			}

			// Shares(53): INT
			public static class Shares
			{
				public const uint tag = 53;
			}

			// Side(54): CHAR
			public static class Side
			{
				public const uint tag = 54;
				public const char BUY = '1';
				public const char SELL = '2';
				public const char BUY_MINUS = '3';
				public const char SELL_PLUS = '4';
				public const char SELL_SHORT = '5';
				public const char SELL_SHORT_EXEMPT = '6';
				public const char UNDISCLOSED = '7';
				public const char CROSS = '8';
			}

			// Symbol(55): CHAR
			public static class Symbol
			{
				public const uint tag = 55;
			}

			// TargetCompID(56): CHAR
			public static class TargetCompID
			{
				public const uint tag = 56;
			}

			// TargetSubID(57): CHAR
			public static class TargetSubID
			{
				public const uint tag = 57;
			}

			// Text(58): CHAR
			public static class Text
			{
				public const uint tag = 58;
			}

			// TimeInForce(59): CHAR
			public static class TimeInForce
			{
				public const uint tag = 59;
				public const char DAY = '0';
				public const char GOOD_TILL_CANCEL = '1';
				public const char AT_THE_OPENING = '2';
				public const char IMMEDIATE_OR_CANCEL = '3';
				public const char FILL_OR_KILL = '4';
				public const char GOOD_TILL_CROSSING = '5';
				public const char GOOD_TILL_DATE = '6';
			}

			// TransactTime(60): UTCTIMESTAMP
			public static class TransactTime
			{
				public const uint tag = 60;
			}

			// Urgency(61): CHAR
			public static class Urgency
			{
				public const uint tag = 61;
				public const char NORMAL = '0';
				public const char FLASH = '1';
				public const char BACKGROUND = '2';
			}

			// ValidUntilTime(62): UTCTIMESTAMP
			public static class ValidUntilTime
			{
				public const uint tag = 62;
			}

			// SettlmntTyp(63): CHAR
			public static class SettlmntTyp
			{
				public const uint tag = 63;
				public const char REGULAR = '0';
				public const char CASH = '1';
				public const char NEXT_DAY = '2';
				public const char T_PLUS_2 = '3';
				public const char T_PLUS_3 = '4';
				public const char T_PLUS_4 = '5';
				public const char FUTURE = '6';
				public const char WHEN_ISSUED = '7';
				public const char SELLERS_OPTION = '8';
				public const char T_PLUS_5 = '9';
			}

			// FutSettDate(64): LOCALMKTDATE
			public static class FutSettDate
			{
				public const uint tag = 64;
			}

			// SymbolSfx(65): CHAR
			public static class SymbolSfx
			{
				public const uint tag = 65;
			}

			// ListID(66): CHAR
			public static class ListID
			{
				public const uint tag = 66;
			}

			// ListSeqNo(67): INT
			public static class ListSeqNo
			{
				public const uint tag = 67;
			}

			// ListNoOrds(68): INT
			public static class ListNoOrds
			{
				public const uint tag = 68;
			}

			// ListExecInst(69): CHAR
			public static class ListExecInst
			{
				public const uint tag = 69;
			}

			// AllocID(70): CHAR
			public static class AllocID
			{
				public const uint tag = 70;
			}

			// AllocTransType(71): CHAR
			public static class AllocTransType
			{
				public const uint tag = 71;
				public const char NEW = '0';
				public const char REPLACE = '1';
				public const char CANCEL = '2';
				public const char PRELIMINARY = '3';
				public const char CALCULATED = '4';
			}

			// RefAllocID(72): CHAR
			public static class RefAllocID
			{
				public const uint tag = 72;
			}

			// NoOrders(73): INT
			public static class NoOrders
			{
				public const uint tag = 73;
			}

			// AvgPrxPrecision(74): INT
			public static class AvgPrxPrecision
			{
				public const uint tag = 74;
			}

			// TradeDate(75): LOCALMKTDATE
			public static class TradeDate
			{
				public const uint tag = 75;
			}

			// ExecBroker(76): CHAR
			public static class ExecBroker
			{
				public const uint tag = 76;
			}

			// OpenClose(77): CHAR
			public static class OpenClose
			{
				public const uint tag = 77;
				public const char CLOSE = 'C';
				public const char OPEN = 'O';
			}

			// NoAllocs(78): INT
			public static class NoAllocs
			{
				public const uint tag = 78;
			}

			// AllocAccount(79): CHAR
			public static class AllocAccount
			{
				public const uint tag = 79;
			}

			// AllocShares(80): INT
			public static class AllocShares
			{
				public const uint tag = 80;
			}

			// ProcessCode(81): CHAR
			public static class ProcessCode
			{
				public const uint tag = 81;
				public const char REGULAR = '0';
				public const char SOFT_DOLLAR = '1';
				public const char STEP_IN = '2';
				public const char STEP_OUT = '3';
				public const char SOFT_DOLLAR_STEP_IN = '4';
				public const char SOFT_DOLLAR_STEP_OUT = '5';
				public const char PLAN_SPONSOR = '6';
			}

			// NoRpts(82): INT
			public static class NoRpts
			{
				public const uint tag = 82;
			}

			// RptSeq(83): INT
			public static class RptSeq
			{
				public const uint tag = 83;
			}

			// CxlQty(84): INT
			public static class CxlQty
			{
				public const uint tag = 84;
			}

			// NoDlvyInst(85): INT
			public static class NoDlvyInst
			{
				public const uint tag = 85;
			}

			// DlvyInst(86): CHAR
			public static class DlvyInst
			{
				public const uint tag = 86;
			}

			// AllocStatus(87): INT
			public static class AllocStatus
			{
				public const uint tag = 87;
				public const int ACCEPTED = 0;
				public const int REJECTED = 1;
				public const int PARTIAL_ACCEPT = 2;
				public const int RECEIVED = 3;
			}

			// AllocRejCode(88): INT
			public static class AllocRejCode
			{
				public const uint tag = 88;
				public const int UNKNOWN_ACCOUNT = 0;
				public const int INCORRECT_QUANTITY = 1;
				public const int INCORRECT_AVERAGE_PRICE = 2;
				public const int UNKNOWN_EXECUTING_BROKER_MNEMONIC = 3;
				public const int COMMISSION_DIFFERENCE = 4;
				public const int UNKNOWN_ORDERID = 5;
				public const int UNKNOWN_LISTID = 6;
				public const int OTHER = 7;
			}

			// Signature(89): DATA
			public static class Signature
			{
				public const uint tag = 89;
			}

			// SecureDataLen(90): LENGTH
			public static class SecureDataLen
			{
				public const uint tag = 90;
			}

			// SecureData(91): DATA
			public static class SecureData
			{
				public const uint tag = 91;
			}

			// BrokerOfCredit(92): CHAR
			public static class BrokerOfCredit
			{
				public const uint tag = 92;
			}

			// SignatureLength(93): LENGTH
			public static class SignatureLength
			{
				public const uint tag = 93;
			}

			// EmailType(94): CHAR
			public static class EmailType
			{
				public const uint tag = 94;
				public const char NEW = '0';
				public const char REPLY = '1';
				public const char ADMIN_REPLY = '2';
			}

			// RawDataLength(95): LENGTH
			public static class RawDataLength
			{
				public const uint tag = 95;
			}

			// RawData(96): DATA
			public static class RawData
			{
				public const uint tag = 96;
			}

			// PossResend(97): CHAR
			public static class PossResend
			{
				public const uint tag = 97;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// EncryptMethod(98): INT
			public static class EncryptMethod
			{
				public const uint tag = 98;
				public const int NONE = 0;
				public const int PKCS = 1;
				public const int DES = 2;
				public const int PKCS_DES = 3;
				public const int PGP_DES = 4;
				public const int PGP_DES_MD5 = 5;
				public const int PEM_DES_MD5 = 6;
			}

			// StopPx(99): FLOAT
			public static class StopPx
			{
				public const uint tag = 99;
			}

			// ExDestination(100): CHAR
			public static class ExDestination
			{
				public const uint tag = 100;
			}

			// CxlRejReason(102): INT
			public static class CxlRejReason
			{
				public const uint tag = 102;
				public const int TOO_LATE_TO_CANCEL = 0;
				public const int UNKNOWN_ORDER = 1;
			}

			// OrdRejReason(103): INT
			public static class OrdRejReason
			{
				public const uint tag = 103;
				public const int BROKER_OPTION = 0;
				public const int UNKNOWN_SYMBOL = 1;
				public const int EXCHANGE_CLOSED = 2;
				public const int ORDER_EXCEEDS_LIMIT = 3;
				public const int TOO_LATE_TO_ENTER = 4;
				public const int UNKNOWN_ORDER = 5;
				public const int DUPLICATE_ORDER = 6;
			}

			// IOIQualifier(104): CHAR
			public static class IOIQualifier
			{
				public const uint tag = 104;
				public const char ALL_OR_NONE = 'A';
				public const char AT_THE_CLOSE = 'C';
				public const char IN_TOUCH_WITH = 'I';
				public const char LIMIT = 'L';
				public const char MORE_BEHIND = 'M';
				public const char AT_THE_OPEN = 'O';
				public const char TAKING_A_POSITION = 'P';
				public const char AT_THE_MARKET = 'Q';
				public const char PORTFOLIO_SHOW_N = 'S';
				public const char THROUGH_THE_DAY = 'T';
				public const char VERSUS = 'V';
				public const char INDICATION = 'W';
				public const char CROSSING_OPPORTUNITY = 'X';
				public const char AT_THE_MIDPOINT = 'Y';
				public const char PRE_OPEN = 'Z';
			}

			// WaveNo(105): CHAR
			public static class WaveNo
			{
				public const uint tag = 105;
			}

			// Issuer(106): CHAR
			public static class Issuer
			{
				public const uint tag = 106;
			}

			// SecurityDesc(107): CHAR
			public static class SecurityDesc
			{
				public const uint tag = 107;
			}

			// HeartBtInt(108): INT
			public static class HeartBtInt
			{
				public const uint tag = 108;
			}

			// ClientID(109): CHAR
			public static class ClientID
			{
				public const uint tag = 109;
			}

			// MinQty(110): INT
			public static class MinQty
			{
				public const uint tag = 110;
			}

			// MaxFloor(111): INT
			public static class MaxFloor
			{
				public const uint tag = 111;
			}

			// TestReqID(112): CHAR
			public static class TestReqID
			{
				public const uint tag = 112;
			}

			// ReportToExch(113): CHAR
			public static class ReportToExch
			{
				public const uint tag = 113;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// LocateReqd(114): CHAR
			public static class LocateReqd
			{
				public const uint tag = 114;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// OnBehalfOfCompID(115): CHAR
			public static class OnBehalfOfCompID
			{
				public const uint tag = 115;
			}

			// OnBehalfOfSubID(116): CHAR
			public static class OnBehalfOfSubID
			{
				public const uint tag = 116;
			}

			// QuoteID(117): CHAR
			public static class QuoteID
			{
				public const uint tag = 117;
			}

			// NetMoney(118): FLOAT
			public static class NetMoney
			{
				public const uint tag = 118;
			}

			// SettlCurrAmt(119): FLOAT
			public static class SettlCurrAmt
			{
				public const uint tag = 119;
			}

			// SettlCurrency(120): CHAR
			public static class SettlCurrency
			{
				public const uint tag = 120;
			}

			// ForexReq(121): CHAR
			public static class ForexReq
			{
				public const uint tag = 121;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// OrigSendingTime(122): UTCTIMESTAMP
			public static class OrigSendingTime
			{
				public const uint tag = 122;
			}

			// GapFillFlag(123): CHAR
			public static class GapFillFlag
			{
				public const uint tag = 123;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// NoExecs(124): INT
			public static class NoExecs
			{
				public const uint tag = 124;
			}

			// CxlType(125):  CHAR
			public static class CxlType
			{
				public const uint tag = 125;
			}

			// ExpireTime(126): UTCTIMESTAMP
			public static class ExpireTime
			{
				public const uint tag = 126;
			}

			// DKReason(127): CHAR
			public static class DKReason
			{
				public const uint tag = 127;
				public const char UNKNOWN_SYMBOL = 'A';
				public const char WRONG_SIDE = 'B';
				public const char QUANTITY_EXCEEDS_ORDER = 'C';
				public const char NO_MATCHING_ORDER = 'D';
				public const char PRICE_EXCEEDS_LIMIT = 'E';
				public const char OTHER = 'Z';
			}

			// DeliverToCompID(128): CHAR
			public static class DeliverToCompID
			{
				public const uint tag = 128;
			}

			// DeliverToSubID(129): CHAR
			public static class DeliverToSubID
			{
				public const uint tag = 129;
			}

			// IOINaturalFlag(130): CHAR
			public static class IOINaturalFlag
			{
				public const uint tag = 130;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// QuoteReqID(131): CHAR
			public static class QuoteReqID
			{
				public const uint tag = 131;
			}

			// BidPx(132): FLOAT
			public static class BidPx
			{
				public const uint tag = 132;
			}

			// OfferPx(133): FLOAT
			public static class OfferPx
			{
				public const uint tag = 133;
			}

			// BidSize(134): INT
			public static class BidSize
			{
				public const uint tag = 134;
			}

			// OfferSize(135): INT
			public static class OfferSize
			{
				public const uint tag = 135;
			}

			// NoMiscFees(136): INT
			public static class NoMiscFees
			{
				public const uint tag = 136;
			}

			// MiscFeeAmt(137): FLOAT
			public static class MiscFeeAmt
			{
				public const uint tag = 137;
			}

			// MiscFeeCurr(138): CHAR
			public static class MiscFeeCurr
			{
				public const uint tag = 138;
			}

			// MiscFeeType(139): CHAR
			public static class MiscFeeType
			{
				public const uint tag = 139;
				public const char REGULATORY = '1';
				public const char TAX = '2';
				public const char LOCAL_COMMISSION = '3';
				public const char EXCHANGE_FEES = '4';
				public const char STAMP = '5';
				public const char LEVY = '6';
				public const char OTHER = '7';
				public const char MARKUP = '8';
			}

			// PrevClosePx(140): FLOAT
			public static class PrevClosePx
			{
				public const uint tag = 140;
			}

			// ResetSeqNumFlag(141): CHAR
			public static class ResetSeqNumFlag
			{
				public const uint tag = 141;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// SenderLocationID(142): CHAR
			public static class SenderLocationID
			{
				public const uint tag = 142;
			}

			// TargetLocationID(143): CHAR
			public static class TargetLocationID
			{
				public const uint tag = 143;
			}

			// OnBehalfOfLocationID(144): CHAR
			public static class OnBehalfOfLocationID
			{
				public const uint tag = 144;
			}

			// DeliverToLocationID(145): CHAR
			public static class DeliverToLocationID
			{
				public const uint tag = 145;
			}

			// NoRelatedSym(146): INT
			public static class NoRelatedSym
			{
				public const uint tag = 146;
			}

			// Subject(147): CHAR
			public static class Subject
			{
				public const uint tag = 147;
			}

			// Headline(148): CHAR
			public static class Headline
			{
				public const uint tag = 148;
			}

			// URLLink(149): CHAR
			public static class URLLink
			{
				public const uint tag = 149;
			}

			// ExecType(150): CHAR
			public static class ExecType
			{
				public const uint tag = 150;
				public const char NEW = '0';
				public const char PARTIAL_FILL = '1';
				public const char FILL = '2';
				public const char DONE_FOR_DAY = '3';
				public const char CANCELLED = '4';
				public const char REPLACE = '5';
				public const char PENDING_CANCEL_REPLACE = '6';
				public const char STOPPED = '7';
				public const char REJECTED = '8';
				public const char SUSPENDED = '9';
				public const char PENDING_NEW = 'A';
				public const char CALCULATED = 'B';
				public const char EXPIRED = 'C';
			}

			// LeavesQty(151): INT
			public static class LeavesQty
			{
				public const uint tag = 151;
			}

			// CashOrderQty(152): FLOAT
			public static class CashOrderQty
			{
				public const uint tag = 152;
			}

			// AllocAvgPx(153): FLOAT
			public static class AllocAvgPx
			{
				public const uint tag = 153;
			}

			// AllocNetMoney(154): FLOAT
			public static class AllocNetMoney
			{
				public const uint tag = 154;
			}

			// SettlCurrFxRate(155): FLOAT
			public static class SettlCurrFxRate
			{
				public const uint tag = 155;
			}

			// SettlCurrFxRateCalc(156): CHAR
			public static class SettlCurrFxRateCalc
			{
				public const uint tag = 156;
				public const char MULTIPLY = 'M';
				public const char DIVIDE = 'D';
			}

			// NumDaysInterest(157): INT
			public static class NumDaysInterest
			{
				public const uint tag = 157;
			}

			// AccruedInterestRate(158): FLOAT
			public static class AccruedInterestRate
			{
				public const uint tag = 158;
			}

			// AccruedInterestAmt(159): FLOAT
			public static class AccruedInterestAmt
			{
				public const uint tag = 159;
			}

			// SettlInstMode(160): CHAR
			public static class SettlInstMode
			{
				public const uint tag = 160;
				public const char DEFAULT = '0';
				public const char STANDING_INSTRUCTIONS_PROVIDED = '1';
				public const char SPECIFIC_ALLOCATION_ACCOUNT_OVERRIDING = '2';
				public const char SPECIFIC_ALLOCATION_ACCOUNT_STANDING = '3';
			}

			// AllocText(161): CHAR
			public static class AllocText
			{
				public const uint tag = 161;
			}

			// SettlInstID(162): CHAR
			public static class SettlInstID
			{
				public const uint tag = 162;
			}

			// SettlInstTransType(163): CHAR
			public static class SettlInstTransType
			{
				public const uint tag = 163;
				public const char CANCEL = 'C';
				public const char NEW = 'N';
				public const char REPLACE = 'R';
			}

			// EmailThreadID(164): CHAR
			public static class EmailThreadID
			{
				public const uint tag = 164;
			}

			// SettlInstSource(165): CHAR
			public static class SettlInstSource
			{
				public const uint tag = 165;
				public const char BROKERS_INSTRUCTIONS = '1';
				public const char INSTITUTIONS_INSTRUCTIONS = '2';
			}

			// SettlLocation(166): STRING
			public static class SettlLocation
			{
				public const uint tag = 166;
				public const string CEDEL = "CED";
				public const string DEPOSITORY_TRUST_COMPANY = "DTC";
				public const string EUROCLEAR = "EUR";
				public const string FEDERAL_BOOK_ENTRY = "FED";
				public const string LOCAL_MARKET_SETTLE_LOCATION = "ISO Country Code";
				public const string PHYSICAL = "PNY";
				public const string PARTICIPANT_TRUST_COMPANY = "PTC";
			}

			// SecurityType(167): STRING
			public static class SecurityType
			{
				public const uint tag = 167;
				public const string BANKERS_ACCEPTANCE = "BA";
				public const string CERTIFICATE_OF_DEPOSIT = "CD";
				public const string COLLATERALIZE_MORTGAGE_OBLIGATION = "CMO";
				public const string CORPORATE_BOND = "CORP";
				public const string COMMERCIAL_PAPER = "CP";
				public const string CORPORATE_PRIVATE_PLACEMENT = "CPP";
				public const string COMMON_STOCK = "CS";
				public const string FEDERAL_HOUSING_AUTHORITY = "FHA";
				public const string FEDERAL_HOME_LOAN = "FHL";
				public const string FEDERAL_NATIONAL_MORTGAGE_ASSOCIATION = "FN";
				public const string FOREIGN_EXCHANGE_CONTRACT = "FOR";
				public const string FUTURE = "FUT";
				public const string GOVERNMENT_NATIONAL_MORTGAGE_ASSOCIATION = "GN";
				public const string TREASURIES_PLUS_AGENCY_DEBENTURE = "GOVT";
				public const string MUTUAL_FUND = "MF";
				public const string MORTGAGE_INTEREST_ONLY = "MIO";
				public const string MORTGAGE_PRINCIPLE_ONLY = "MPO";
				public const string MORTGAGE_PRIVATE_PLACEMENT = "MPP";
				public const string MISCELLANEOUS_PASS_THRU = "MPT";
				public const string MUNICIPAL_BOND = "MUNI";
				public const string NO_ISITC_SECURITY_TYPE = "NONE";
				public const string OPTION = "OPT";
				public const string PREFERRED_STOCK = "PS";
				public const string REPURCHASE_AGREEMENT = "RP";
				public const string REVERSE_REPURCHASE_AGREEMENT = "RVRP";
				public const string STUDENT_LOAN_MARKETING_ASSOCIATION = "SL";
				public const string TIME_DEPOSIT = "TD";
				public const string US_TREASURY_BILL = "USTB";
				public const string WARRANT = "WAR";
				public const string CATS_TIGERS_LIONS = "ZOO";
			}

			// EffectiveTime(168): UTCTIMESTAMP
			public static class EffectiveTime
			{
				public const uint tag = 168;
			}

			// StandInstDbType(169): INT
			public static class StandInstDbType
			{
				public const uint tag = 169;
				public const int OTHER = 0;
				public const int DTC_SID = 1;
				public const int THOMSON_ALERT = 2;
				public const int A_GLOBAL_CUSTODIAN = 3;
			}

			// StandInstDbName(170): CHAR
			public static class StandInstDbName
			{
				public const uint tag = 170;
			}

			// StandInstDbID(171): CHAR
			public static class StandInstDbID
			{
				public const uint tag = 171;
			}

			// SettlDeliveryType(172): INT
			public static class SettlDeliveryType
			{
				public const uint tag = 172;
			}

			// SettlDepositoryCode(173): CHAR
			public static class SettlDepositoryCode
			{
				public const uint tag = 173;
			}

			// SettlBrkrCode(174): CHAR
			public static class SettlBrkrCode
			{
				public const uint tag = 174;
			}

			// SettlInstCode(175): CHAR
			public static class SettlInstCode
			{
				public const uint tag = 175;
			}

			// SecuritySettlAgentName(176): CHAR
			public static class SecuritySettlAgentName
			{
				public const uint tag = 176;
			}

			// SecuritySettlAgentCode(177): CHAR
			public static class SecuritySettlAgentCode
			{
				public const uint tag = 177;
			}

			// SecuritySettlAgentAcctNum(178): CHAR
			public static class SecuritySettlAgentAcctNum
			{
				public const uint tag = 178;
			}

			// SecuritySettlAgentAcctName(179): CHAR
			public static class SecuritySettlAgentAcctName
			{
				public const uint tag = 179;
			}

			// SecuritySettlAgentContactName(180): CHAR
			public static class SecuritySettlAgentContactName
			{
				public const uint tag = 180;
			}

			// SecuritySettlAgentContactPhone(181): CHAR
			public static class SecuritySettlAgentContactPhone
			{
				public const uint tag = 181;
			}

			// CashSettlAgentName(182): CHAR
			public static class CashSettlAgentName
			{
				public const uint tag = 182;
			}

			// CashSettlAgentCode(183): CHAR
			public static class CashSettlAgentCode
			{
				public const uint tag = 183;
			}

			// CashSettlAgentAcctNum(184): CHAR
			public static class CashSettlAgentAcctNum
			{
				public const uint tag = 184;
			}

			// CashSettlAgentAcctName(185): CHAR
			public static class CashSettlAgentAcctName
			{
				public const uint tag = 185;
			}

			// CashSettlAgentContactName(186): CHAR
			public static class CashSettlAgentContactName
			{
				public const uint tag = 186;
			}

			// CashSettlAgentContactPhone(187): CHAR
			public static class CashSettlAgentContactPhone
			{
				public const uint tag = 187;
			}

			// BidSpotRate(188): FLOAT
			public static class BidSpotRate
			{
				public const uint tag = 188;
			}

			// BidForwardPoints(189): FLOAT
			public static class BidForwardPoints
			{
				public const uint tag = 189;
			}

			// OfferSpotRate(190): FLOAT
			public static class OfferSpotRate
			{
				public const uint tag = 190;
			}

			// OfferForwardPoints(191): FLOAT
			public static class OfferForwardPoints
			{
				public const uint tag = 191;
			}

			// OrderQty2(192): FLOAT
			public static class OrderQty2
			{
				public const uint tag = 192;
			}

			// FutSettDate2(193): LOCALMKTDATE
			public static class FutSettDate2
			{
				public const uint tag = 193;
			}

			// LastSpotRate(194): FLOAT
			public static class LastSpotRate
			{
				public const uint tag = 194;
			}

			// LastForwardPoints(195): FLOAT
			public static class LastForwardPoints
			{
				public const uint tag = 195;
			}

			// AllocLinkID(196): CHAR
			public static class AllocLinkID
			{
				public const uint tag = 196;
			}

			// AllocLinkType(197): INT
			public static class AllocLinkType
			{
				public const uint tag = 197;
				public const int F_X_NETTING = 0;
				public const int F_X_SWAP = 1;
			}

			// SecondaryOrderID(198): CHAR
			public static class SecondaryOrderID
			{
				public const uint tag = 198;
			}

			// NoIOIQualifiers(199): INT
			public static class NoIOIQualifiers
			{
				public const uint tag = 199;
			}

			// MaturityMonthYear(200): MONTHYEAR
			public static class MaturityMonthYear
			{
				public const uint tag = 200;
			}

			// PutOrCall(201): INT
			public static class PutOrCall
			{
				public const uint tag = 201;
				public const int PUT = 0;
				public const int CALL = 1;
			}

			// StrikePrice(202): FLOAT
			public static class StrikePrice
			{
				public const uint tag = 202;
			}

			// CoveredOrUncovered(203): INT
			public static class CoveredOrUncovered
			{
				public const uint tag = 203;
				public const int COVERED = 0;
				public const int UNCOVERED = 1;
			}

			// CustomerOrFirm(204): INT
			public static class CustomerOrFirm
			{
				public const uint tag = 204;
				public const int CUSTOMER = 0;
				public const int FIRM = 1;
			}

			// MaturityDay(205): DAYOFMONTH
			public static class MaturityDay
			{
				public const uint tag = 205;
			}

			// OptAttribute(206): CHAR
			public static class OptAttribute
			{
				public const uint tag = 206;
			}

			// SecurityExchange(207): CHAR
			public static class SecurityExchange
			{
				public const uint tag = 207;
			}

			// NotifyBrokerOfCredit(208): CHAR
			public static class NotifyBrokerOfCredit
			{
				public const uint tag = 208;
				public const char NO = 'N';
				public const char YES = 'Y';
			}

			// AllocHandlInst(209): INT
			public static class AllocHandlInst
			{
				public const uint tag = 209;
				public const int MATCH = 1;
				public const int FORWARD = 2;
				public const int FORWARD_AND_MATCH = 3;
			}

			// MaxShow(210): INT
			public static class MaxShow
			{
				public const uint tag = 210;
			}

			// PegDifference(211): FLOAT
			public static class PegDifference
			{
				public const uint tag = 211;
			}
		}
	}
}
